<?php

/**
 * Blog_Model_Doctrine_BlogTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Blog
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Blog_Model_Doctrine_BlogTranslation extends Blog_Model_Doctrine_BaseBlogTranslation
{

}