<?php

/**
 * Blog_Model_Doctrine_BlogTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Blog_Model_Doctrine_BlogTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Blog_Model_Doctrine_BlogTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Blog_Model_Doctrine_BlogTranslation');
    }
}