<?php

/**
 * Blog_Model_Doctrine_Blog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Blog
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Blog_Model_Doctrine_Blog extends Blog_Model_Doctrine_BaseBlog
{
    public static $blogEntryPhotoDimensions = array(
        '126x126' => 'Admin thumbnail',                  // admin
        '290x135' => 'Main photo'
    );
    
    public static function getBlogEntryPhotoDimensions() {
        return self::$blogEntryPhotoDimensions;
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function getPublishDate() {
        return $this->_get('publish_date');
    }
    
    public function getMetatagId() {
        return $this->_get('metatag_id');    
    }
    
    public function setUp() {
        parent::setUp();
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        $this->hasMany('Media_Model_Doctrine_Photo as Photos', array(
            'local' => 'photo_root_id',
            'foreign' => 'root_id'
        ));
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
    }
}