<?php if(isset($this->category)): ?>
    <?php if($this->category->getNode()->getParent()): ?>
        <?php echo $this->partial('category-path.phtml', 'product', array('category' => $this->category->getNode()->getParent(), 'language' => $this->language)) ?>
    <?php endif; ?>
    <?php if($this->category['level'] > 0 &&  $this->category->Translation[$this->language]->slug): ?>
            <a href="<?php echo $this->url(array('category' => $this->category->Translation[$this->language]->slug), 'domain-i18n:category') ?>">
                <?php echo ucfirst($this->category->Translation[$this->language]->name); ?>
            </a>
    <?php endif; ?>
<?php endif; ?>