<?php

/**
 * Censor_Model_Doctrine_BaseIP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip
 * 
 * @package    Admi
 * @subpackage Censor
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Censor_Model_Doctrine_BaseIp extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('censor_ip');
        $this->hasColumn('ip', 'string', 255, array(
             'primary' => true,
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}