<?php

/**
 * Censor_Model_Doctrine_CensorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Censor_Model_Doctrine_CensorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Censor_Model_Doctrine_CensorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Censor_Model_Doctrine_Censor');
    }
}