<div class="separator" style="height:17px;"></div>
                        
<div class="block_home_slider">
        <div id="home_slider" class="flexslider">
        <ul class="slides">
            <?php foreach($this->lastNews as $news): ?>
                
            <li>
                <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>" >
                    <div class="slide">
                        <img src="/media/photos/<?php echo $news['PhotoRoot']['offset'];?>/610x292/<?php echo $news['PhotoRoot']['filename'];?>" alt="">
                        <div class="caption">
                            <p class="title"><?php echo $news['Translation'][$this->language]['title']; ?></p>
                            <p><?php echo MF_Text::truncate(strip_tags($news['Translation'][$this->language]['content']),120,'words'); ?></p>
                        </div>
                    </div>
                </a>
            </li>

            
            <?php endforeach; ?>
        </ul>
    </div>

    <script type="text/javascript">
                                        $(function () {
                                                $('#home_slider').flexslider({
                                                        animation : 'slide',
                                                        controlNav : true,
                                                        directionNav : true,
                                                        animationLoop : true,
                                                        slideshow : false,
                                                        useCSS : false
                                                });

                                        });
                                </script>
</div>

<div class="line_2" style="margin:34px 0px 28px;"></div>