<?php foreach($this->newsList as $category => $newses): ?>
    <h3 style="font-size:16px;"><?php echo $category; ?></h3>
    <div class="line_4" style="margin:-4px 0px 18px;"></div>
    <div class="block_topic_news">
        <?php foreach($newses as $news): 
            $photoRoot = $news['PhotoRoot'];
            ?>
                                    <article class="block_topic_post">
                                        <p class="title"><a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>">Many desktop publishing packages and web page editors now use.</a></p>
                                        <div class="f_pic"><a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>" class="general_pic_hover scale"><img src="/media/photos/<?php echo $photoRoot['offset'];?>/256x122/<?php echo $photoRoot['filename']; ?>" alt=""></a></div>
                                    <p class="text"><?php echo MF_Text::truncate(strip_tags($news['Translation'][$this->language]['content']),60,'words'); ?></p>
                                    <div class="info">
                                           <div class="date"><p><?php echo MF_Text::timeFormat($news['publish_date'],'Y-m-d'); ?></p></div>

<!--                                        <div class="r_part">
                                            <div class="category"><p><a href="#">Business</a></p></div>
                                            <a href="#" class="views">183</a>
                                        </div>-->
                                    </div>
                                </article>
        <?php endforeach; ?>
     </div>
     <div class="line_3" style="margin:20px 0px 24px;"></div>
<?php endforeach; ?>

                        
                        
                        