<?php $item = $this->item; ?>
<div class="news">
    <div class="newsHeader">
        <h1 class="news-header">Aktualności</h1>
        <div class="path">
                <a href="<?php echo $this->url(array(),'domain-homepage'); ?>" title=""><?php echo $this->translate('Home') ;?></a> / <a class="curr" href="<?php echo $this->url(array(),'domain-i18n:news'); ?>" title=""><?php echo $this->translate('News') ;?></a>
        </div>
    </div>
	<div class="col-left">
			
			<div class="header">Aktualności</div>
                            <div class="news-container">
                                <?php foreach($this->newsList as $key=>$news): ?>
                                    <div>
                                            <span class="news-date"><?php echo MF_Text::timeFormat($news->publish_date,'Y-m-d'); ?></span>
                                            <a style="font-size:13px;color:#7b7b7b;" href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']), 'domain-news') ?>"><?php echo MF_Text::truncate($news['Translation'][$this->language]['title'],20); ?></a>
                                    </div>
                                <?php endforeach; ?>	
                            </div>
		
	</div>
	<div class="col-right">
            
		<div class="select-ref"> 
                    <?php echo $item['Translation'][$this->language]['title'] ?>
		</div>
                     <?php
                     $is_main = false;
                      if($item->get('PhotoRoot')):
                        $photoRoot = $item->get('PhotoRoot');
                      if(strlen($photoRoot['filename'])){
                          $is_main = true;
                          $photoFirst = $photoRoot;
                      }
                      else{
                          $photoFirst = $item->get('PhotoRoot')->getNode()->getChildren()->getFirst();
                      } 
                      
                      if(strlen($photoFirst['filename'])){
                      ?>
                        <div class="news-image" style="background-image:url('/media/photos/<?php echo $photoFirst['offset'] ?>/400x/<?php echo $photoFirst['filename']; ?>')"></div>
                      <?php }else{ ?>
                            <div class="news-image" style=""></div>
                       <?php } ?>
            <?php endif; ?>
		<div>
                    <?php echo $this->linkService->readLink($item['Translation'][$this->language]['content']); ?>
                    <?php if($item->get('VideoRoot')): 
                        $videoRoot = $item->get('VideoRoot');
                        foreach($videoRoot->getNode()->getChildren() as $video):
                        ?>
                        <iframe class="newsVideo" src="<?php echo $video->url; ?>" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 
                    <?php 
                        endforeach;
                    endif; ?>
                        
                            <?php if($item->get('PhotoRoot')&&count($item['Photos'])>1): ?>
                        <?php if(!(!$is_first && count($item['Photos'])==2)): ?>
                        <div class="gallery-container">    
                                <h1 style="color:#555555;margin-bottom:10px;">Galeria</h1>
                                 <div class="gallery-box">

                                <ul>
                               <?php foreach($item->get('PhotoRoot')->getNode()->getChildren() as $key => $photo):
                                   if(!$is_main && $key==0)
                                       continue;
                                   ?>
                                                <li style="background:url('/media/photos/<?php echo $photo['offset'] ?>/400x/<?php echo $photo['filename'] ?>');background-size:100% 100%;width:160px;height:160px;margin:0px 4px;">
                                                    <a href="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['title'] ?>" onclick="return hs.expand(this)">
                                                        <img src="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['title'] ?>" style="" />
                                                    </a>
                                                </li>


                                    <?php endforeach; ?>
                                </ul>	

                                        <img alt="" src="/images/g_left.png" class="g_left">

                                        <img alt="" src="/images/g_right.png" class="g_right">

                                </div>
                          </div>
                        <?php endif; ?>
                            <?php endif; ?>
                        
                    <?php if($item->get('AttachmentRoot')&& $item->get('AttachmentRoot')->getNode()->hasChildren()): 
                        $attachmentRoot = $item->get('AttachmentRoot'); ?>
                        <div class="newsAttachment"><h5>Załączniki: </h5>
                        <?php
                        
                        foreach($attachmentRoot->getNode()->getChildren() as $attachment):
                        ?>
                        <a download href="/media/attachments/<?php echo $attachment->getFilename(); ?>"><?php echo $attachment['Translation'][$this->language]['title']; ?></a>
                    <?php endforeach; ?>
                         </div>
                  <?php  endif; ?>
                       
		</div>
        </div>
<div class="clear"></div>
		
</div>