<div class="block_popular_posts">
        <h4>Popularne tematy</h4>

        <?php foreach($this->popularNews as $news):
            $photoRoot = $news['PhotoRoot'];
            ?>
        <div class="article">
            <div class="pic">
                    <a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>" class="w_hover">
                            <img src="/media/photos/<?php echo $photoRoot['offset'];?>/67x45/<?php echo $photoRoot['filename']; ?>" alt="">
                            <span></span>
                    </a>
            </div>

            <div class="text">
                    <p class="title"><a href="<?php echo $this->url(array('slug' => $news['Translation'][$this->language]['slug']),'domain-news-article'); ?>"><?php echo $news['Translation'][$this->language]['title']; ?></a></p>
                    <div class="date"><p><?php echo MF_Text::polishTimeFormat($news['publish_date'], 'j M Y'); ?></p></div>
                    <div class="icons">
                        <ul>
                            <li><a href="#" class="views"><?php echo $news['views']; ?></a></li>
                            <li><a href="#" class="comments"> <?php echo $news['comment_count']; ?></a></li>
                        </ul>
                    </div>
            </div>
        </div>
        
        
        <div class="line_3"></div>
        <?php endforeach; ?>

</div>