<script type="text/javascript">
    $(document).ready(function() {
       var selected = $(".menu").find(".<?php echo $this->category->Translation[$this->language]->slug; ?>").addClass("current-menu-item");
       $(selected).parentsUntil(".menu").children().addClass("expanded");
    });   		  
</script>
<span class="catDescription"><?php echo $this->collection['Translation'][$this->language]->description; ?></span>
<section class="colums popular-objects">
    <ul>
        <?php
      
        foreach($this->products as $product):
            
?>
      <div class="col5">
              <div class="img imgWrap"><a href="<?php  echo $this->url(array('lang' => $this->language, 'product' => $product['Translation'][$this->language]->slug), 'domain-i18n:product'); ?>">
                    <?php if($product['PhotoRoot']['filename']): ?>
                        <img src="/media/photos/<?php echo $product['PhotoRoot']['offset'] ?>/170x/<?php echo $product['PhotoRoot']['filename'] ?>" alt="">
                    <?php else: ?>
                        <img src="/images/temp/prod05.jpg" alt="" />
                    <?php endif; ?>
                         <p class="imgDescription"></p>
                         <span class="imgDescriptionText"><?php echo $product['Translation'][$this->language]->name; ?></span>
                    </a>
                 
              </div>
       </div>

        <?php endforeach; ?>
    </ul>
<!--    <div class="wp-pagenavi">
        <?php //echo $this->paginationControl($this->paginator, 'Sliding', 'product_pagination_control.phtml') ?>
    </div>-->
</section>