<div class="productBox productPageBox">
    <?php if(is_object($this->page)): ?>
        <h1><?php echo $this->page['Translation'][$this->language]['title']; ?></h1>
        <?php echo $this->page['Translation'][$this->language]['content']; ?>
    <?php endif; ?>
    <?php foreach($this->products as $newProduct):
        $photoRoot = $newProduct->get('PhotoRoot');
        ?>
    <div>
        <a href="<?php echo $this->url(array('product' => $newProduct['Translation'][$this->language]['slug']),'domain-i18n:product'); ?>">
            <span class="productImgWrapper">
                <img src="/media/photos/<?php echo $photoRoot['offset']; ?>/<?php echo $this->photoDimension; ?>/<?php echo $photoRoot['filename']; ?>" />
            </span>
            <span class="productNameWrapper">
                <h3><?php echo $newProduct['Translation'][$this->language]['name']; ?></h3>
                <?php echo "Identyfikator: ".$newProduct['id']; ?>
            </span>
        </a>
    </div>
    <?php endforeach; ?>
</div>