<script>
    jQuery(document).ready(function($) {
  $('.product-gallery').royalSlider({
    fullscreen: {
      enabled: true,
      nativeFS: true
    },
    
     controlNavigation: 'thumbnails',

    
    
    autoScaleSlider: true, 
    autoScaleSliderWidth: 300,     
    autoScaleSliderHeight: 200,
    loop: true,
    navigateByClick: true,
    numImagesToPreload:2,
    arrowsNav:true,
    arrowsNavAutoHide: false,
    sliderDrag: true,
    sliderTouch: false,
    arrowsNavHideOnTouch: true,
    keyboardNavEnabled: true,
    fadeinLoadedSlide: true,
    globalCaption: false,
    globalCaptionInside: false,
    thumbs: {
      appendSpan: true,
      firstMargin: false,
      paddingBottom: 4,
      fitInViewport: true,
      drag: false,
      arrows: true,
      marginTop: 10
    }
  });
});
</script>

<div class="productBoxes productCart">
    <?php 
    $category = $this->product['Categories'][0]; 
    if($category->getNode()->hasParent()):
            $parent = $category->getNode()->getParent();
            if(strlen($parent['Translation'][$this->language][name])): ?>
              <div class="boxList">
                <a href="#">Maszyny do drewna - <?php echo $parent['Translation'][$this->language][name]." - ".$category['Translation'][$this->language]['name']; ?><span class="productName"><?php echo $this->product->Translation[$this->language]->name;  ?></span></a>
                <span id="product_id">Identyfikator: <span><?php echo $this->product->id; ?></span></span>
            </div>  
       <?php else: ?>
            <div class="boxList">
                <a href="#">Maszyny do drewna - <?php echo $category['Translation'][$this->language]['name']; ?><br /><span class="productName"><?php echo $this->product->Translation[$this->language]->name;  ?></span></a>
                <span id="product_id">Identyfikator: <span><?php echo $this->product->id; ?></span></span>
            </div> 
        <?php endif;
        endif;?>
        <div class="row">
            <div class="col span_6 fwImage">
                <div class="product-gallery" class="royalSlider videoGallery rsWithThumbs rsDefault rsWithThumbsVer">
                    <?php foreach($this->product['Photos'] as $photo): ?>
                    <div class="rsContent">
                        <a class="rsImg" data-rsw="820" data-rsh="475" data-rsbigimg="/media/photos/<?php echo $photo['offset']; ?>/<?php echo $photo['filename']; ?>" href="/media/photos/<?php echo $photo['offset']; ?>/<?php echo $photo['filename']; ?>">
                            <?php echo $this->product['Translation'][$this->language]['name']; ?><<img width="96" height="72" class="rsTmb" src="/media/photos/<?php echo $photo['offset']; ?>/<?php echo $this->photoDimension; ?>/<?php echo $photo['filename']; ?>">
                        </a>
                   </div>
                    <?php endforeach; ?>

                </div>
            </div>
        </div>
    <div class="bottomWrapper">
          <div class="productLeftBoxText">
              <?php if($this->product->sold): ?>
              <div class="productSold">
                  <span>Ten produkt nie jest aktualnie dostępny.</span> Skontaktuj się z nami aby dowiedzieć się więcej.
              </div>
              <?php endif; ?>
              <?php echo $this->product->Translation[$this->language]->description; ?>
          </div>
        <div class="productRightBox">

            <div id="fb" class="fb-like" data-href="<?php echo 'http://' . $_SERVER['SERVER_NAME']. Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
            <br />
            <span id="pin">
                <a href="//www.pinterest.com/pin/create/button/?url=<?php echo 'http://' .$_SERVER['SERVER_NAME']. Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>&media=Image&description=" data-pin-do="buttonPin" data-pin-config="none"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" /></a>
            </span><div id="result"></div>
            <div class="clear"></div>

            <?php if($this->messages()->count()): ?>
            <div class="message">
                <?php echo $this->messages()->render(); ?>
            </div>
            <?php endif; ?>
            <!-- wpcf7 start -->
            <h4>Zapytaj o produkt</h4>
            <form class="wpcf7" method="post" action="<?php echo $this->form->getAction() ?>">
                <?php echo $this->form->csrf; ?>
                <fieldset>
                    <label><span class="text-color">*</span> <?php echo $this->form->name->getLabel(); ?>:</label>
                    <?php echo $this->form->name->setDecorators(array('ViewHelper')); ?>
                    <span class="error"><?php echo $this->form->name->setDecorators(array('Errors')); ?></span>
                </fieldset>

                <fieldset>
                    <label><span class="text-color">*</span> <?php echo $this->form->email->getLabel(); ?>:</label>
                    <?php echo $this->form->email->setDecorators(array('ViewHelper')); ?>
                    <span class="error"><?php echo $this->form->email->setDecorators(array('Errors')); ?></span>
                </fieldset>

                <fieldset>
                    <label><span class="text-color"></span> <?php echo $this->form->phone->getLabel(); ?>:</label>
                    <?php echo $this->form->phone->setDecorators(array('ViewHelper')); ?>
                    <span class="error"><?php echo $this->form->phone->setDecorators(array('Errors')); ?></span>
                </fieldset>

                <fieldset>
                    <label><span class="text-color">*</span> <?php echo $this->form->message->getLabel(); ?>:</label>
                    <?php echo $this->form->message->setDecorators(array('ViewHelper')); ?>
                    <span class="error"><?php echo $this->form->message->setDecorators(array('Errors')); ?></span>
                </fieldset>

                <?php echo $this->form->captcha; ?>

                <?php echo $this->form->submit; ?>

            </form><!-- wpcf7 end -->
        </div>
        <div class="clear"></div>
    </div>
</div>