<div class="productTop">
   	    <div class="titleL">&nbsp;</div>
   		<div class="titleBG">
		   <strong class="productTitle">Wszystkie produkty producenta <?php echo $this->producer['Translation'][$this->language]['name']; ?></strong>
   		</div>
		<div class="titleP">&nbsp;</div>
</div>

 <div class="sftlo">

    <div class="tekst">
        
       
            <img src="/media/photos/<?php echo $this->producer->get('PhotoRoot')->getOffset(); ?>/<?php echo $this->producer->get('PhotoRoot')->getFilename(); ?>"  alt="<?php echo $this->producer['Translation'][$this->language]['name']; ?>" title="<?php echo $this->producer['Translation'][$this->language]['name']; ?>">
    </div>
    <div class="boxik" >
        
        <?php foreach($this->producer['Products'] as $product): 
            
            ?>
    	         <div class="prodImg" >
                      <?php 
                      if($product->get('PhotoRoot')->getNode()->hasChildren()):
                            $photos = $product->get('PhotoRoot')->getNode()->getChildren();
                            $photo = $photos[0];
                        ?>
                     <a href="<?php echo $this->url(array('product' => $product['Translation'][$this->language]->slug), 'domain-i18n:product'); ?>">
                         <img src="/media/photos/<?php echo $photo->getOffset(); ?>/200x/<?php echo $photo->getFilename(); ?>" alt="<?php echo $product['Translation'][$this->language]['name'];?>"><br><?php echo $product['Translation'][$this->language]['name'];?>
                     </a>
                     <?php else: ?>
                         <img src="/images/temp/prod05.jpg" alt="" /> <br><?php echo $product['Translation'][$this->language]['name'];?>
                     <?php endif; ?>
                 </div>
    	<?php endforeach; ?>         
    </div>


 </div>