<div class="productBoxes">
    
    <div class="boxList">
        <a href="#">Wyniki wyszukiwania - <?php echo $this->query; ?></a>
    </div>     
    
    <div class="productBox">
        <?php foreach($this->products as $product):
            $photoRoot = $product->get('PhotoRoot');
            ?>
        <div>
            <a href="<?php echo $this->url(array('product' => $product['Translation'][$this->language]['slug']),'domain-i18n:product'); ?>">
                <span class="productImgWrapper">
                    <img src="/media/photos/<?php echo $photoRoot['offset']; ?>/<?php echo $this->photoDimension; ?>/<?php echo $photoRoot['filename']; ?>" />
                </span>
                <span class="productNameWrapper">
                    <h3><?php echo $product['Translation'][$this->language]['name']; ?> </h3>
                    <?php echo "Identyfikator: ".$product['id']; ?><br />
                </span>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>