<?php

/**
 * Product_Model_Doctrine_BaseDimension
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $width
 * @property integer $height
 * @property Doctrine_Collection $DimensionPrices
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseDimension extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_dimension');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('width', 'integer', 3, array(
             'type' => 'integer',
             'length' => '3',
             ));
        $this->hasColumn('height', 'integer', 3, array(
             'type' => 'integer',
             'length' => '3',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product_Model_Doctrine_DimensionPrice as DimensionPrices', array(
             'local' => 'id',
             'foreign' => 'dimension_id'));
    }
}