<?php

/**
 * Product_Model_Doctrine_BaseDimensionPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $dimension_id
 * @property decimal $price
 * @property integer $availability
 * @property integer $discount_id
 * @property boolean $new
 * @property boolean $promoted
 * @property boolean $promotion
 * @property decimal $promotion_price
 * @property boolean $most_frequently_purchased
 * @property Product_Model_Doctrine_Product $Product
 * @property Product_Model_Doctrine_Dimension $Dimension
 * @property Product_Model_Doctrine_Discount $Discount
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Product_Model_Doctrine_BaseDimensionPrice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('product_dimension_price');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('dimension_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('availability', 'integer', 1, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '1',
             ));
        $this->hasColumn('discount_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('promoted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('promotion', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('promotion_price', 'decimal', null, array(
             'type' => 'decimal',
             'default' => 0,
             ));
        $this->hasColumn('most_frequently_purchased', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product_Model_Doctrine_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('Product_Model_Doctrine_Dimension as Dimension', array(
             'local' => 'dimension_id',
             'foreign' => 'id'));

        $this->hasOne('Product_Model_Doctrine_Discount as Discount', array(
             'local' => 'discount_id',
             'foreign' => 'id'));
    }
}