<?php

/**
 * Product_Model_Doctrine_Collection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_Collection extends Product_Model_Doctrine_BaseCollection
{
    public static $collectionPhotoDimensions = array(
        '126x126' => 'Photo in admin panel', // admin
        '170x' => 'Thumb',
        '980x' => 'Photo',
    );
    
     public static $collectionMainPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '120x' => 'Thumb',
        '170x' => 'Thumb2',
        '400x' => 'Biggest Thumb',
        '980x' => 'Main photo'
    );
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function getMetatagId() {
        return $this->_get('metatag_id');    
    }
    
    public function isStatus() {
        return $this->_get('status');
    }
    public function getSlug() {
        return $this->_get('slug');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function getDiscountId() {
        return $this->_get('discount_id');    
    }
    
    public function setDiscountId($discountId) {
        $this->_set('discount_id', $discountId);
    }
    
    public static function getCollectionPhotoDimensions() {
        return self::$collectionPhotoDimensions;
    }
    
    public static function getCollectionMainPhotoDimensions() {
        return self::$collectionMainPhotoDimensions;
    } 
    
    public function setUp() {
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
        parent::setUp();
    }
}