<?php

/**
 * Product_Model_Doctrine_CollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_CollectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_CollectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Collection');
    }
      public function getCollectionQuery() {
        $q = $this->createQuery('col');
        $q->addSelect('col.*');
        $q->addSelect('tr.*');
        $q->leftJoin('col.Translation tr');
        return $q;
    }
    
    public function getMainCollectionsQuery() {
        $q = $this->createQuery('cat');
        $q->addSelect('cat.*');
        $q->addSelect('ct.*');
        $q->leftJoin('cat.Translation ct');
        $q->andWhere('cat.level = ?', 1);
        return $q;
    }
}