<?php

/**
 * Product_Model_Doctrine_DimensionPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_DimensionPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_DimensionPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_DimensionPrice');
    }
    
    public function getDimensionPriceQuery() {
        $q = $this->createQuery('p');
        $q->addSelect('p.*');
//        $q->addSelect('pr.*');
//        $q->addSelect('ph.*');
//        $q->addSelect('pt.*');
//        $q->leftJoin('p.Translation pt');
//        $q->leftJoin('pro.PhotoRoot pr');
//        $q->leftJoin('pro.Photos ph');
        return $q;
    }
}