<?php

/**
 * Product_Model_Doctrine_DimensionPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_DimensionPrice extends Product_Model_Doctrine_BaseDimensionPrice
{
    public function isPromoted() {
        return $this->_get('promoted');
    }
    
    public function setPromoted($promoted = true) {
        $this->_set('promoted', $promoted);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setDiscountId($discountId) {
        $this->_set('discount_id', $discountId);
    }
    public function getAvailability() {
        return $this->_get('availability');
    }
    public function setAvailability($value) {
        $this->_set('availability',$value);
    }
    public function getMostFrequentlyPurchased() {
        return $this->_get('most_frequently_purchased');
    }
    public function setMostFrequentlyPurchased($value) {
        $this->_set('most_frequently_purchased',$value);
    }
}