<?php

/**
 * Product_Model_Doctrine_Dimension
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Product
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product_Model_Doctrine_Dimension extends Product_Model_Doctrine_BaseDimension
{
    public function getHeight() {
        return $this->_get('height');
    }
    public function getWidth() {
        return $this->_get('width');
    }
}