<?php

/**
 * Product_Model_Doctrine_ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Product_Model_Doctrine_ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Product_Model_Doctrine_ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product_Model_Doctrine_Product');
    }
    
    public function getProductQuery() {
        $q = $this->createQuery('p');
        $q->addSelect('p.*');
        $q->addSelect('pt.*');
        $q->addSelect('c.*');
        $q->addSelect('ct.*');
        $q->addSelect('pr.*');
        $q->leftJoin('p.Translation pt');
        $q->leftJoin('p.Category c');
        $q->leftJoin('c.Translation ct');
        $q->leftJoin('p.PhotoRoot pr');
        return $q;
    }

     public function getShortQuery() {
        $q = $this->createQuery('pro');
        $q->addSelect('pro.*');
        return $q;
    }
    public function getIdsProductsQuery() {
        $q = $this->createQuery('pro');
        $q->addSelect('pro.*');
        $q->addSelect('cat.*');
        $q->leftJoin('pro.Category cat');
        $q->where('pro.status = ?', array(1));
        return $q;
    }
    
    public function getProducerIdsProductsQuery($producerId) {
        $q = $this->createQuery('pro');
        $q->addSelect('pro.*');
        $q->addSelect('cat.*');
        $q->addSelect('pr.*');
        $q->leftJoin('pro.Category cat');
        $q->where('pro.status = ?', array(1));
        $q->groupBy('pro.id');
        $q->andWhere('pr.id = ?', $producerId);
        return $q;
    }
}