<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('offer_category', 'offer_category_metatag_id_default_metatag_id');
    }

    public function down()
    {
        $this->createForeignKey('offer_category', 'offer_category_metatag_id_default_metatag_id', array(
             'name' => 'offer_category_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
    }
}