<script>
    jQuery(document).ready(function(){
       
                  jQuery('.fullwidthabnner').revolution({
                      auto: true,
                      delay:4500,
                      startheight:122,
                      startwidth:391,

                      hideThumbs:10,

                      thumbWidth:100,                         // Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                      thumbHeight:50,
                      thumbAmount:5,

                      navigationType:"none",                // bullet, thumb, none
                      navigationArrows:"none",                // nexttobullets, solo (old name verticalcentered), none

                      navigationStyle:"round",                // round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom

                      navigationHAlign:"center",              // Vertical Align top,center,bottom
                      navigationVAlign:"bottom",              // Horizontal Align left,center,right
                      navigationHOffset:0,
                      navigationVOffset:20,

                      soloArrowLeftHalign:"left",
                      soloArrowLeftValign:"center",
                      soloArrowLeftHOffset:20,
                      soloArrowLeftVOffset:0,

                      soloArrowRightHalign:"right",
                      soloArrowRightValign:"center",
                      soloArrowRightHOffset:20,
                      soloArrowRightVOffset:0,

                      touchenabled:"on",                      // Enable Swipe Function : on/off
                      onHoverStop:"on",                       // Stop Banner Timet at Hover on Slide on/off

                      stopAtSlide:-1,
                      stopAfterLoops:-1,

                      hideCaptionAtLimit:0,         // It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
                      hideAllCaptionAtLilmit:0,       // Hide all The Captions if Width of Browser is less then this value
                      hideSliderAtLimit:0,          // Hide the whole slider, and stop also functions if Width of Browser is less than this value

                      shadow:1,                               //0 = no Shadow, 1,2,3 = 3 Different Art of Shadows  (No Shadow in Fullwidth Version !)
                      fullWidth:"off"                          // Turns On or Off the Fullwidth Image Centering in FullWidth Modus
                  });
        
    });
</script>


            <!-- BEGIN SLIDER -->
    <div class="page-slider margin-bottom-40" style="width: <?php echo $this->photoDimensionWidth; ?>px; margin:0 auto;">
      <div class="fullwidthbanner-container revolution-slider">
        <div class="fullwidthabnner">
          <ul id="revolutionul">
            <?php foreach($this->slider['main']['Slides'] as $slide): ?>
            <?php if($slide['level'] == 0) continue; ?>
            

            
            <!-- THE NEW SLIDE -->
               <li data-transition="fade" data-slotamount="8" data-masterspeed="700" data-delay="5000" data-thumb="/assets/frontend/pages/img/revolutionslider/thumbs/thumb2.jpg"> <!-- THE MAIN IMAGE IN THE FIRST SLIDE -->
              <img src="/media/photos/<?php echo $slide['PhotoRoot']['offset'] ?>/<?php echo $this->photoDimension; ?>/<?php echo $slide['PhotoRoot']['filename'] ?>" alt="Slider background">
              
               
            </li>    
            
            <?php endforeach; ?>
                               
                        
                </ul>
                <div class="tp-bannertimer tp-bottom"></div>
            </div>
        </div>
    </div>