<div class="row-fluid">

    <div class="span6">

        <div class="box">

            <div class="title">

                <h4> 
                    <span>Text fields</span>
                </h4>

            </div>
            <div class="content">

                <form class="form-horizontal" action="#">

                    <?php echo $this->form->name ?>
                    <?php echo $this->form->group ?>
                    <?php echo $this->form->submit ?>
                    
                </form>

            </div>

        </div><!-- End .box -->

    </div><!-- End .span6 -->
    
</div>