<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#template_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-parameter-template-data', 'offer') ?>",
        "aaSorting": [[ 0, "asc" ]],
        "aoColumns": [
            null,
            null,
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#template_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    
});
</script>
<div class="row-fluid">

    <div class="span6">

        <div id="new_parameter" class="box">

            <div class="title">
                <h4>
                    <span class="icon16 entypo-icon-settings"></span>
                    <span><?php echo $this->translate('New parameter') ?></span>
                </h4>
            </div>
            <div class="content">
                <form class="form-horizontal" action="<?php echo $this->adminUrl('add-parameter-template', 'offer') ?>" method="post">
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->unit ?>
                    <?php echo $this->form->range ?> 
                    <?php echo $this->form->description ?> 
                    <?php echo $this->form->submit ?>
                    <?php echo $this->form->id ?>
                </form>
            </div>

        </div><!-- End .box -->

    </div> <!-- End span6 -->
    
    <div class="span6">
        
        <div class="box">

            <div class="title">
                <h4>
                    <span><?php echo $this->translate('Parameters') ?></span>
                </h4>
            </div>
            <div class="content noPad clearfix">
                <table id="template_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered " width="100%">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Name') ?></th>
                            <th><?php echo $this->translate('Unit') ?></th>
                            <th><?php echo $this->translate('Range') ?></th>
                            <th><?php echo $this->translate('Actions') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            
        </div> <!-- End box -->
        
    </div>

</div>