<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#offer_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-offer-data', 'offer') ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { sWidth: '150px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#offer_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 silk-icon-calculator"></span>
                    <span><?php echo $this->translate('Offers') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="offer_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Title') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>


</div>