<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#category_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        <?php if(isset($this->parent)): ?>
        "sAjaxSource": "<?php echo $this->adminUrl('list-category-data', 'offer', array('id' => $this->parent->getId())) ?>",
        <?php else: ?>
        "sAjaxSource": "<?php echo $this->adminUrl('list-category-data', 'offer') ?>",
        <?php endif; ?>
        "aaSorting": [[ 1, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#category_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="page-header">
            <h4><?php echo $this->translate('Price list') ?></h4>
        </div>
        
        <table class="table table-bordered">
            <tbody>
                <thead>
                    <tr>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('1 month') ?></th>
                        <th><?php echo $this->translate('3 months') ?></th>
                    </tr>
                </thead>
                <?php foreach($this->categoryPriceTree->fetchRoot()->getNode()->getChildren() as $child): ?>
                
                <?php if($child->getNode()->getLevel() == 1 && $child->getNode()->getChildren()): ?>
                <tr>
                    <td colspan="3"><b><?php echo $child['name'] ?></b></td>
                </tr>
                
                <?php foreach($child->getNode()->getChildren() as $child): ?>
                <tr>
                    <td><?php echo $child['name'] ?></td>
                    <?php foreach($this->periods as $period): ?>
                        <?php $p = false; foreach($child['Prices'] as $price): ?>
                        <?php if($price['period'] == (int) $period): ?>
                        <td><?php echo $price['price'] ?> PLN</td>
                        <?php $p = true; endif; ?>
                        <?php endforeach; ?>
                        <?php if($p == false): ?>
                        <td></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                <?php endforeach; ?>
                
                <?php else: ?>

                <tr>
                    <td><b><?php echo $child['name'] ?></b></td>
                    <?php foreach($this->periods as $period): ?>
                        <?php $p = false; foreach($child['Prices'] as $price): ?>
                        <?php if($price['period'] == (int) $period): ?>
                        <td><?php echo $price['price'] ?> PLN</td>
                        <?php $p = true; endif; ?>
                        <?php endforeach; ?>
                        <?php if($p == false): ?>
                        <td></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                
                <?php endif; ?>
                
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </div>

    <div class="span6">
        
        <div class="box">

            <div class="title">

                <h4 class="clearfix">
                    <span class="icon16 cut-icon-tree"></span>
                    <span><?php echo $this->translate('Category tree') ?></span>
                    <form class="box-form right" action="<?php echo $this->form->getAction() ?>" method="post">
                        <span class="span8">
                            <input type="text" name="<?php echo $this->form->name->getName() ?>" class="search-query span2 text" placeholder="<?php echo $this->translate('Name') ?>">
                        </span>
                        <span class="span4">
                            <button class="btn btn-success btn-small" type="submit"><?php echo $this->translate('Add') ?></button>
                        </span>
                        <?php echo $this->form->parent_id ?>
                    </form>
                </h4>
            </div>
            <div class="content">
                
                <div id="category_tree">
                    <?php echo $this->partial('category-tree.phtml', 'offer', array('tree' => $this->categoryTree, 'parent' => $this->parent)) ?>
                </div>
                
            </div>

        </div><!-- End .box -->
        
        <div class="box">

            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edycja') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="category_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>
            
        </div>

    </div>


</div>