<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('guests_post', 'author_name');
        $this->removeColumn('guests_post', 'author_city');
        $this->removeColumn('guests_post', 'content');
        $this->addColumn('guests_post', 'name', 'string', '255', array(
             ));
        $this->addColumn('guests_post', 'city', 'string', '255', array(
             ));
        $this->addColumn('guests_post', 'message', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('guests_post', 'author_name', 'string', '255', array(
             ));
        $this->addColumn('guests_post', 'author_city', 'string', '255', array(
             ));
        $this->addColumn('guests_post', 'content', 'clob', '', array(
             ));
        $this->removeColumn('guests_post', 'name');
        $this->removeColumn('guests_post', 'city');
        $this->removeColumn('guests_post', 'message');
    }
}