<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('guests_post', 'post_id');
    }

    public function down()
    {
        $this->addColumn('guests_post', 'post_id', 'integer', '4', array(
             ));
    }
}