<article class="grid_8">
<h1><?php echo $this->gallery['Translation'][$this->language]['name'] ?></h1>
<?php echo $this->gallery['Translation'][$this->language]['description'] ?>
<?php if($this->gallery->get('PhotoRoot')){ ?>
    <div class="gallery-container gallery-list">

                <div class="gallery-box">
                        <ul>
                            <?php foreach($this->gallery->get('PhotoRoot')->getNode()->getChildren() as $photo): ?>
                                <li>
                                    <a href="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['title'] ?>"
                                       data-lightview-group='<?php echo $this->gallery['Translation'][$this->language]['slug'] ?>'
                                       data-lightview-title="<?php echo $photo['title'] ?>"
                                       class='lightview' 
                                       data-lightview-options="
                                           width: 800,
                                           height: 460,
                                           viewport: 'false',
                                         "
                                       >
                                        <img src="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $this->photoDimension; ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['title'] ?>" />
                                    </a>
                                    <div class="photoTitle">
                                        <?php echo $photo['title'] ?>
                                    </div>
                                </li>
                                <?php endforeach; ?>
                        </ul>	


                </div>

            </div>
<?php
}
?>
</article>