<div class="main-title">
        <h2>Galeria</h2>
        <span>Lista galerii</span>
</div>

<div class="photo-galleries">
        <?php foreach($this->paginator as $gallery): ?>
            <div class="item">
                <div class="item-header">
                        <a href="<?php echo $this->url(array('slug' => $gallery['Translation'][$this->language]['slug']),'domain-i18n:gallery'); ?>" class="image-hover" data-path-hover="M 34,56 45,34 63,41 64,66 47,76 z">
                                <figure>
                                        <img src="/media/photos/<?php echo $gallery['PhotoRoot']['offset']; ?>/265x273/<?php echo $gallery['PhotoRoot']['filename']; ?>" alt="<?php echo $gallery['Translation'][$this->language]['title']; ?>" />
                                        <svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M 0,100 0,99 50,97 100,99 100,100 z" fill="<?php echo MF_Text::getCatColor($gallery['Category']['slug']); ?>" /></svg>
                                        <figcaption>
                                                <span class="hover-text"><i class="fa fa-search"></i></span>
                                        </figcaption>
                                </figure>
                        </a>
                </div>
                <div class="item-content">
                        <div class="content-category">
                                <a href="<?php echo $this->url(array('slug' => $gallery['Translation'][$this->language]['slug']),'domain-i18n:gallery'); ?>" class="cat-<?php echo $gallery['Category']['slug']; ?>-title"><?php  echo $gallery['Category']['title'] ?></a>
                        </div>
                        <h3><a href="<?php echo $this->url(array('slug' => $gallery['Translation'][$this->language]['slug']),'domain-i18n:gallery'); ?>"><?php echo $gallery['Translation'][$this->language]['title']; ?></a></h3>
                        <p><?php echo MF_Text::getCatColor($gallery['Category']['slug']); ?></p>
                        <a href="<?php echo $this->url(array('slug' => $gallery['Translation'][$this->language]['slug']),'domain-i18n:gallery'); ?>" class="read-more-link">Zobacz galerie<i class="fa fa-angle-double-right"></i></a>
                </div>
        </div>
        <?php endforeach; ?>
</div>
 <div class="pagination">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'gallery_pagination_control.phtml'); ?>
</div>  
