<?php if(isset($this->tree)): ?>
<ul id="treeData" style="display: none;" class="folder">
<?php elseif(isset($this->subtree)): ?>
<ul>
<?php endif; ?>

    <?php if(isset($this->tree)): ?>
    
        <?php foreach($this->tree->fetchRoots() as $item): ?>
        <li id="node<?php echo $item->getId() ?>" class="<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?> folder"><a href="<?php echo $this->adminUrl('list-category', 'offer', array('id' => $item->getId())) ?>"><?php echo $item->getName() ?></a>
            <?php if($item->getNode()->getChildren()): ?>
            <?php echo $this->partial('category-tree.phtml', 'offer', array('subtree' => $item->getNode()->getChildren(), 'parent' => $this->parent)) ?>
            <?php endif; ?>
        </li>
        <li id="trash"  data="addClass:'trash'"><?php echo $this->translate('Trash') ?></li>
        <?php endforeach; ?>
    
    <?php elseif(isset($this->subtree)): ?>
    
        <?php foreach($this->subtree as $item): ?>
        <li id="node<?php echo $item->getId() ?>" class="<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?>"><a href="<?php echo $this->adminUrl('edit-category', 'offer', array('id' => $item->getId())) ?>"><?php echo $item->getName() ?></a>
            <?php if($item->getNode()->getChildren()): ?>
            <?php echo $this->partial('category-tree.phtml', 'offer', array('subtree' => $item->getNode()->getChildren(), 'parent' => $this->parent)) ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
        
    <?php endif; ?>
    
</ul>