<script type="text/javascript">
$(document).ready(function() {
    
//    var oTable = $("#article_table").dataTable( {
//        "sPaginationType": "full_numbers",
//        "oLanguage": {
//            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
//        },
//        "bFilter": true,
//        "bDestroy": true,
//        "bProcessing": true,
//        "bServerSide": true,
//        "bLengthChange": false,
//        "sAjaxSource": "<?php // echo $this->adminUrl('list-article-data', 'news') ?>",
//        "aaSorting": [[ 2, "desc" ]],
//        "aoColumns": [
//            null,
//            null,
//            null,
//            { "bSortable": false, sWidth: '50px' }
//        ]
//    });
    
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog'
	});
  
    $("#itemContainer").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();

        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-article-photo', 'article') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger("update");
                        }
                    }
                });

                $('#explorer').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                }
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });

    $("#itemContainer").delegate(".actionBtn .delete", "click", function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php echo $this->adminUrl('remove-article-photo', 'article') ?>/id/"+$('#id').val(),
            data: data,
            success: function(resp) {
                if(resp.status == "success") {
                    $("#main_photo_container").html(resp.body);
                }
            }
        });
        $("#itemContainer").trigger("update");
    });
    
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit article') ?> <?php echo $this->article->getTitle() ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
                    
                    <?php echo $this->form->title ?>
                    <?php echo $this->form->content ?>
                    <?php echo $this->form->id ?>
                    
                    <div class="page-header">
                        <h4><?php echo $this->translate('Main photo') ?></h4>
                    </div>
                    
                    <div id="itemContainer">
                        <ul id="main_photo_container" class="galleryView center">
                            <li class="pull-left">
                                <?php if($this->article->get('PhotoRoot')->getOffset()): ?>
                                <a id="main_photo" href="/media/photos/<?php echo $this->article->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->article->get('PhotoRoot')->getTitle() ?>">
                                    <img src="/media/photos/<?php echo $this->article->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->article->get('PhotoRoot')->getOffset() ?>/<?php echo $this->article->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->article->get('PhotoRoot')->getTitle() ?>">
                                </a>
                                <div class="actionBtn">
                                    <a href="<?php echo $this->adminUrl('edit-article-photo', 'article', array('article-id' => $this->article['id'], 'id' => $this->article->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                    <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                    <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                </div>
                                <?php else: ?>
                                <a id="main_photo" href="/images/gallery/1.jpg" title="<?php echo $this->translate('No photo') ?>">
                                    <img src="/images/gallery/preload.png" data-original="/images/gallery/thumbnails/1.jpg" alt="<?php echo $this->translate('No photo') ?>">
                                </a>
                                <div class="actionBtn">
                                    <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                </div>
                                <?php endif; ?>
                            </li>
                        </ul>
                    </div>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-article', 'article') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                    
                </form>
            
            </div>
            
        </div>
        
    </div>

    <?php /*
    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edycja') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="article_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Title') ?></th>
                        <th><?php echo $this->translate('Category') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>
    */ ?>

</div>

        
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
    