<?php

/**
 * Newsletter_Model_Doctrine_BaseCourseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $organizer
 * @property timestamp $start_date
 * @property timestamp $finish_date
 * @property clob $additional_info
 * @property integer $course_name_id
 * @property integer $photo_root
 * @property Doctrine_Collection $CourseProfile
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Newsletter_Model_Doctrine_BaseCourseProfile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('job_course_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('organizer', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finish_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('additional_info', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('course_name_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('photo_root', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Newsletter_Model_Doctrine_CourseName as CourseProfile', array(
             'local' => 'course_profile_id',
             'foreign' => 'id'));
    }
}