<?php

/**
 * Newsletter_Model_Doctrine_BaseDrivingProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $driving_id
 * @property integer $profile_id
 * @property Newsletter_Model_Doctrine_DrivingLicense $DrivingProfile
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Newsletter_Model_Doctrine_BaseDrivingProfile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('job_driving_profile');
        $this->hasColumn('driving_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('profile_id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Newsletter_Model_Doctrine_DrivingLicense as DrivingProfile', array(
             'local' => 'driving_id',
             'foreign' => 'id'));
    }
}