<?php

/**
 * Newsletter_Model_Doctrine_BaseUniversityStudyType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Newsletter_Model_Doctrine_UniversityStudyProfile $UniversityStudyProfile
 * @property Doctrine_Collection $UniversityStudyType
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Newsletter_Model_Doctrine_BaseUniversityStudyType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('job_university_study_type');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Newsletter_Model_Doctrine_UniversityStudyProfile as UniversityStudyProfile', array(
             'local' => 'id',
             'foreign' => 'study_type_id'));

        $this->hasMany('Newsletter_Model_Doctrine_UniversityStudyProfile as UniversityStudyType', array(
             'local' => 'study_type_id',
             'foreign' => 'id'));
    }
}