<?php

/**
 * Newsletter_Model_Doctrine_BaseUniversityStudyProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $start_date
 * @property timestamp $finish_date
 * @property string $diploma_number
 * @property string $diploma_grade
 * @property integer $profile_id
 * @property integer $university_study_id
 * @property integer $study_type_id
 * @property integer $photo_root
 * @property Newsletter_Model_Doctrine_UniversityStudyType $UniversityStudyProfile
 * @property Doctrine_Collection $StudyType
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Newsletter_Model_Doctrine_BaseUniversityStudyProfile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('job_university_study_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finish_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('diploma_number', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('diploma_grade', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('university_study_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('study_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('photo_root', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Newsletter_Model_Doctrine_UniversityStudyType as UniversityStudyProfile', array(
             'local' => 'id',
             'foreign' => 'study_type_id'));

        $this->hasMany('Newsletter_Model_Doctrine_UniversityStudyType as StudyType', array(
             'local' => 'study_type_id',
             'foreign' => 'id'));
    }
}