<?php

/**
 * Newsletter_Model_Doctrine_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Newsletter
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Newsletter_Model_Doctrine_Message extends Newsletter_Model_Doctrine_BaseMessage
{
   
     public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
     public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
     public function setContent($content) {
        $this->_set('id', $content);
    }
    
    public function getContent() {
        return $this->_get('content');
    }
     public function setSent($value=1){
        $this->_set('sent',$value);
    }
    
    public function setSendAt($value){
        $this->_set('send_at',$value);
    }
    
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product_Model_Doctrine_Category as Categories', array(
             'refClass' => 'Newsletter_Model_Doctrine_MessageCategory',
             'local' => 'message_id',
             'foreign' => 'category_id'));


        
    }
}