<?php if(isset($this->items)): ?>
    <?php foreach($this->items as $key => $item): ?>
    <li>        
        <a id="<?php echo $key ?>" href="<?php echo $this->url(array('category' => $item['categorySlug']), 'domain-category') ?>"><span><?php echo $item['categoryName']; ?></span><span class="catItemCount"><?php echo $item['counter']; ?></span></a>
    </li>
    <?php endforeach; ?>
<?php endif; ?>   