<ul class='subItem'>
    <?php if(isset($this->categoryTree)): ?>
    
        <?php foreach($this->categoryTree as $item):?>
        <li id="node<?php echo $item->getId() ?>" class="<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?>"><a href="<?php echo $this->url(array('slug' => $item->Translation[$this->language]->slug), 'domain-category'); ?>"><?php echo $item->Translation[$this->language]['name'] ?></a>
            <?php if($item->getNode()->getChildren()): ?>
                <?php echo $this->partial('index/category-menu-tree.phtml', 'product', array('categoryTree' => $item->getNode()->getChildren(), 'parent' => $this->parent, 'language' => $this->language)) ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    
    <?php elseif(isset($this->subtree)): ?>
    
        <?php foreach($this->subtree as $item): ?>
        <li id="node<?php echo $item->getId() ?>" class="<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?>"><a href="<?php echo $this->url(array('slug' => $item->Translation[$this->language]->slug), $item->getRoute()); ?>"><?php echo $item->Translation[$this->language]['title'] ?></a>
            <?php if($item->getNode()->getChildren()): ?>
            <?php echo $this->partial('menu_tree.phtml', 'menu', array('subtree' => $item->getNode()->getChildren(), 'parent' => $this->parent, 'language' => $this->language)) ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
        
    <?php endif; ?>
    
</ul>