<script>
    $(document).ready(function(){
       $('.boxList a').click(function(){
          $('.productBox').css('display','none');
          $('#'+$(this).attr('rel')).css('display','block');
          $('.boxList a').removeClass('boxActive');
          $(this).addClass('boxActive');
       }); 
       
       
    });
</script>
<div class="centerBox">
    <div class="centerImgWrapper">
        <img src="/img/srodek_1.jpg" />
        <div class="centerImg">
            <?php echo $this->action('index','index','slider'); ?>
        </div>
    </div><br><h1>Maszyny do drewna</h1>
    <?php echo $this->homepage->Translation[$this->language]->content; ?>
</div>

<div class="productBoxes">
    <div class="boxList">
        <a href="javascript:void(0)" rel="newProducts" class="boxActive">Nowości w ofercie</a>
        <a href="javascript:void(0)" rel="promotionProducts" >Promocje</a>
        
    </div>
    <div id="promotionProducts" class="productBox" style="display:none">
        <?php foreach($this->promotionProducts as $promotionProduct):
            $photoRoot = $promotionProduct->get('PhotoRoot');
            ?>
        <div>
            <a href="<?php echo $this->url(array('product' => $promotionProduct['Translation'][$this->language]['slug']),'domain-i18n:product'); ?>">
                <span class="productImgWrapper <?php if($promotionProduct->sold){ echo "productImgSold"; }?>">
                    <img src="/media/photos/<?php echo $photoRoot['offset']; ?>/<?php echo $this->photoDimension; ?>/<?php echo $photoRoot['filename']; ?>" />
                </span>
                <span class="productNameWrapper">
                    <h3><?php echo $promotionProduct['Translation'][$this->language]['name']; ?> </h3>
                    <?php echo "Identyfikator: ".$promotionProduct->id; ?><br />
                </span>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
    <div id="newProducts" class="productBox" >
        <?php foreach($this->newProducts as $newProduct):
            $photoRoot = $newProduct->get('PhotoRoot');
            ?>
        <div>
            <a href="<?php echo $this->url(array('product' => $newProduct['Translation'][$this->language]['slug']),'domain-i18n:product'); ?>">
                <span class="productImgWrapper <?php if($newProduct->sold){ echo "productImgSold"; }?>">
                    <img src="/media/photos/<?php echo $photoRoot['offset']; ?>/<?php echo $this->photoDimension; ?>/<?php echo $photoRoot['filename']; ?>" />
                </span>
                <span class="productNameWrapper">
                    <h3><?php echo $newProduct['Translation'][$this->language]['name']; ?></h3>
                    <?php  echo "Identyfikator: ".$newProduct->id;  ?><br />
                </span>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>