
    <div class="topMeta"> 
        <form action="<?php echo $this->url(array(), 'domain-results-searching') ?>" method="get" enctype="application/x-www-form-urlencoded">
            <?php 
            //echo $this->form->phrase; 
            ?>
            
        </form>
         
            <ul class="social">
                <!--<li class="tt"><a href="#"></a></li>-->
                <li class="fb"><a href="#"></a></li>
                <li class="gp"><a href="#"></a></li>
            </ul>
    </div>