
<div class="row-fluid">

    <div class="span12">
        
        <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
            
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span>Edytuj ip <?php echo $this->ip->ip ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                    <?php echo $this->form->ip?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-ip', 'censor') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
            
            </div>
            
        </div>
        
       
            
        </form>
                
    </div>


</div>