<script type="text/javascript">
$(document).ready(function() {

    var oTable = $("#censor_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->adminUrl('list-ip-data', 'censor') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": true, sWidth: '200px' },
            { "bSortable": false, sWidth: '40px' }
        ]
    }).yadcf([
        {
          column_number: 0,
          filter_type: "text"
        },
        {
          column_number: 1,
          filter_type: "text"
        }
        
        
        ]);

    $("#censor_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });

});
</script> 

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil-2"></span>
                    <span>Niecenzuralne słowa</span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-ip', 'censor') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="censor_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Ip') ?></th>
                            <th><?php echo $this->translate('Created') ?></th>
                            <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                        <tr>
                            <th><?php echo $this->translate('Ip') ?></th>
                            <th><?php echo $this->translate('Created') ?></th>
                            <th><?php echo $this->translate('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>

</div>
