<?php

/**
 * Order_Model_Doctrine_BaseOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property clob $attention
 * @property decimal $total_cost
 * @property integer $order_status_id
 * @property integer $delivery_id
 * @property integer $payment_id
 * @property Order_Model_Doctrine_Delivery $Delivery
 * @property Order_Model_Doctrine_Payment $Payment
 * @property Order_Model_Doctrine_OrderStatus $OrderStatus
 * @property Doctrine_Collection $Items
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Order_Model_Doctrine_BaseOrder extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('order_order');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('attention', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('total_cost', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('order_status_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('delivery_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('payment_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Order_Model_Doctrine_Delivery as Delivery', array(
             'local' => 'delivery_id',
             'foreign' => 'id'));

        $this->hasOne('Order_Model_Doctrine_Payment as Payment', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Order_Model_Doctrine_OrderStatus as OrderStatus', array(
             'local' => 'order_status_id',
             'foreign' => 'id'));

        $this->hasMany('Order_Model_Doctrine_Item as Items', array(
             'local' => 'id',
             'foreign' => 'order_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}