<?php

/**
 * Order_Model_Doctrine_BasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $status_service
 * @property string $status
 * @property string $error_code
 * @property integer $payment_type_id
 * @property boolean $invoice
 * @property Order_Model_Doctrine_PaymentType $PaymentType
 * @property Order_Model_Doctrine_Order $Order
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Order_Model_Doctrine_BasePayment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('order_payment');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('status_service', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('error_code', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('payment_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('invoice', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Order_Model_Doctrine_PaymentType as PaymentType', array(
             'local' => 'payment_type_id',
             'foreign' => 'id'));

        $this->hasOne('Order_Model_Doctrine_Order as Order', array(
             'local' => 'id',
             'foreign' => 'payment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}