<?php

/**
 * Order_Model_Doctrine_DiscountCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_DiscountCode extends Order_Model_Doctrine_BaseDiscountCode
{
    public function getDiscount() {
        return $this->_get('discount');
    }
    public function setActive($status) {
        $this->_set('active', $status);
    }
}