<?php

/**
 * Order_Model_Doctrine_Order
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    User
 * @subpackage OrderItem
 * @author     Tomasz Kardas
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_OrderItem extends Order_Model_Doctrine_BaseOrderItem
{
    public function getId() {
        return $this->_get('id');
    }
    
//    public function setUp() {
//        $this->hasOne('User_Model_Doctrine_User as User', array(
//            'local' => 'user_id',
//            'foreign' => 'id'
//        ));
//        parent::setUp();
//    }
}