<?php

/**
 * Attachment_Model_Doctrine_AttachmentSerwis7Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Attachment_Model_Doctrine_AttachmentSerwis7Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Attachment_Model_Doctrine_AttachmentSerwis7Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Attachment_Model_Doctrine_AttachmentSerwis7');
    }
    
    public function getAttachmentQuery() {
        $q = $this->createQuery('a');
        $q->addSelect('a.*');
        $q->addSelect('at.*');
        $q->addSelect('pr.*');
        $q->leftJoin('a.Translation at');
        $q->leftJoin('a.PhotoRoot pr');
        return $q;
    }
}