<?php

/**
 * Attachment_Model_Doctrine_AttachmentSerwis8Translation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Attachment
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Attachment_Model_Doctrine_AttachmentSerwis8Translation extends Attachment_Model_Doctrine_BaseAttachmentSerwis8Translation
{

}