<?php

/**
 * Attachment_Model_Doctrine_AttachmentSerwis1TranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Attachment_Model_Doctrine_AttachmentSerwis1TranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Attachment_Model_Doctrine_AttachmentSerwis1TranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Attachment_Model_Doctrine_AttachmentSerwis1Translation');
    }
}