<?php

/**
 * Attachment_Model_Doctrine_AttachmentSerwis5Translation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Attachment
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Attachment_Model_Doctrine_AttachmentSerwis5Translation extends Attachment_Model_Doctrine_BaseAttachmentSerwis5Translation
{

}