
		<script type="text/javascript" src="/assets/jscript/snap.svg-min.js"></script>
		<script type="text/javascript" src="/assets/jscript/theme-scripts.js"></script>
		<script type="text/javascript" src="/assets/jscript/lightbox.js"></script>
		<script type="text/javascript" src="/assets/jscript/owl.carousel.min.js"></script>
		<script type="text/javascript" src="/assets/jscript/SmoothScroll.min.js"></script>
		<script type="text/javascript" src="/assets/jscript/iscroll.js"></script>
		<script type="text/javascript" src="/assets/jscript/modernizr.custom.50878.js"></script>
		<script type="text/javascript" src="/assets/jscript/dat-menu.js"></script>
<script type="text/javascript" src="/plugins/lightview/js/lightview/lightview.js"></script>
		<script>
			jQuery(document).ready(function() {
				jQuery(".ot-slider").owlCarousel({
					items : 1,
					autoPlay : false,
					stopOnHover : true,
					navigation : true,
					lazyLoad : true,
					singleItem : true,
					pagination : false
				});
                                jQuery(".gallery-shortcode-photos").owlCarousel({
					items : 3,
					autoPlay : false,
					stopOnHover : true,
					navigation : false,
					lazyLoad : true,
					singleItem : false,
					pagination : true
				});

				jQuery(".similar-articles-list .similar-articles").owlCarousel({
					items : 4,
					autoPlay : false,
					stopOnHover : true,
					navigation : false,
					lazyLoad : true,
					singleItem : false,
					pagination : true
				});
				
			});
		</script>

<footer class="footer">
				
				<div class="footer-copyright">
					<!-- BEGIN .wrapper -->
					<div class="wrapper">
						<p class="right">Designed by <strong><a href="varts.pl" target="_blank">varts.pl</a></strong></p>
						<p>&copy; All Rights Reserved <strong>IMAV</strong></p>
					<!-- END .wrapper -->
					</div>
				</div>
				
			<!-- END .footer -->
			</footer>