

				<div class="wrapper">

					<div class="header-left">
						<div class="header-logo">
							<a href="/" class="otanimation"><img src="/images/layout/logo_imav.png" alt="" />
                                                        <img class="header-text" src="/images/layout/tekst_logo.png" alt="" />
                                                        </a>
						</div>
<!--						<div class="header-socials">
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-google-plus"></i></a>
							<a href="#"><i class="fa fa-youtube"></i></a>
							<a href="#"><i class="fa fa-vimeo-square"></i></a>
						</div>-->
					</div>

					<div class="header-right">
						<nav class="main-menu">
                                                   <?php echo $this->partial('menu_main_tree.phtml', 'menu', array('tree' => $this->tree, 'parent' => $this->menuItem, 'language' => $this->language)) ?>
							<div class="search-header" action="search">
								<form action="/wyszukaj" method="POST">
									<input type="search" value="" placeholder="Wyszukaj news" autocomplete="off" required="required" name="search_name" />
									<input type="submit" name="search_submit" value="search" />
								</form>
							</div>
						</nav>
						<nav class="under-menu">
							 <?php echo $this->partial('submenu_main_tree.phtml', 'menu', array('submenu_tree' => $this->submenu_tree, 'parent' => $this->menuItem, 'language' => $this->language)) ?>
						
						</nav>
					</div>

					<div class="clear-float"></div>
					
				<!-- END .wrapper -->
				</div>
		
     