<head>
    <title>BusinessNews</title>

    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="index,follow" />
    <meta name="author" content="varts.pl" />

    <!--[if lt IE 9]>
    <script type="text/javascript" src="/assets/layout/plugins/html5.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="/assets/layout/style.css" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=PT+Sans:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic" rel="stylesheet" type="text/css">

    
	<link rel="stylesheet" href="/css/custom.css">
    
    <script type="text/javascript" src="/assets/layout/js/jquery.js"></script>

    <!-- PrettyPhoto start -->
    <link rel="stylesheet" href="/assets/layout/plugins/prettyphoto/css/prettyPhoto.css" type="text/css">
    <script type="text/javascript" src="/assets/layout/plugins/prettyphoto/jquery.prettyPhoto.js"></script>
    <!-- PrettyPhoto end -->

    <!-- jQuery tools start -->
    <script type="text/javascript" src="/assets/layout/plugins/tools/jquery.tools.min.js"></script>
    <!-- jQuery tools end -->

    <!-- Calendar start -->
    <link rel="stylesheet" href="/assets/layout/plugins/calendar/calendar.css" type="text/css">
    <script type="text/javascript" src="/assets/layout/plugins/calendar/calendar.js"></script>
    <!-- Calendar end -->

    <!-- ScrollTo start -->
    <script type="text/javascript" src="/assets/layout/plugins/scrollto/jquery.scroll.to.min.js"></script>
    <!-- ScrollTo end -->

    <!-- MediaElements start -->
    <link rel="stylesheet" href="/assets/layout/plugins/video-audio/mediaelementplayer.css" >
    <script src="/assets/layout/plugins/video-audio/mediaelement-and-player.js"></script>
    <!-- MediaElements end -->

    <!-- FlexSlider start -->
    <link rel="stylesheet" href="/assets/layout/plugins/flexslider/flexslider.css" type="text/css"/>
    <script type="text/javascript" src="/assets/layout/plugins/flexslider/jquery.flexslider-min.js"></script>
    <!-- FlexSlider end -->

    <!-- iButtons start -->
    <link rel="stylesheet" href="/assets/layout/plugins/ibuttons/css/jquery.ibutton.css" type="text/css"/>
    <script type="text/javascript" src="/assets/layout/plugins/ibuttons/lib/jquery.ibutton.min.js"></script>
    <!-- iButtons end -->

    <link rel="shortcut icon" href="/plugins/eventcalendar/images/favicon.ico" />

	<!-- Grid CSS File (only needed for demo page) -->
	<link rel="stylesheet" href="/plugins/eventcalendar/css/paragridma.css">

	<!-- Core CSS File. The CSS code needed to make eventCalendar works -->
	<link rel="stylesheet" href="/plugins/eventcalendar/css/eventCalendar.css">

	<!-- Theme CSS file: it makes eventCalendar nicer -->
	<link rel="stylesheet" href="/plugins/eventcalendar/css/eventCalendar_theme_responsive.css">
    
    <!-- jQuery Form Plugin start -->
    <script type="text/javascript" src="/assets/layout/plugins/ajaxform/jquery.form.js"></script>
    <!-- jQuery Form Plugin end -->

    <script type="text/javascript" src="/assets/layout/js/main.js"></script>

<script src="/plugins/eventcalendar/js/jquery.eventCalendar.js" type="text/javascript"></script>
    <script type="text/javascript">
            jQuery(function () {
            });
    </script>

</head>