    <?php echo $this->headMeta(); ?>
    <title><?php echo strip_tags($this->headTitle()); ?> - IMAV</title>

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

        <meta name="robots" content="index,follow" />
        <meta name="author" content="varts.pl" />


        <!-- Favicon -->
        <link rel="shortcut icon" href="/assets/images/favicon.png" type="image/x-icon" />

        <!-- Stylesheets -->
        <link type="text/css" rel="stylesheet" href="/css/custom.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/reset.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/font-awesome.min.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/animate.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/main-stylesheet.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/lightbox.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/shortcodes.css" />
        <!-- <link type="text/css" rel="stylesheet" href="/assets/css/custom-fonts.css" /> -->
        <link type="text/css" rel="stylesheet" href="/assets/css/custom-colors.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/responsive.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/owl.carousel.css" />
        <link type="text/css" rel="stylesheet" href="/plugins/royalslider/royalslider.css" />
        <link rel="stylesheet" href="/videoplayer/css/videoPlayerMain.css" type="text/css">
 
  <link rel="stylesheet" href="/videoplayer/css/videoPlayer.theme1.css" type="text/css">
 
  <link rel="stylesheet" href="/videoplayer/css/videoPlayer.theme1_Playlist.css" type="text/css" media="screen"/>
 
  <link rel="stylesheet" href="/videoplayer/css/font-awesome.css" type="text/css">
 
 
 
        <link type="text/css" rel="stylesheet" href="/assets/css/owl.theme.css" />
        <link type="text/css" rel="stylesheet" href="/assets/css/dat-menu.css" />
        <link rel="stylesheet" href="/plugins/flexslider/flexslider.css" type="text/css"/>
        <link class="rs-file" href="/plugins/royalslider/skins/default/rs-default.css" rel="stylesheet">
        <!--[if lte IE 8]>
        <link type="text/css" rel="stylesheet" href="/assets/css/ie-ancient.css" />
        <![endif]-->
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&subset=latin-ext,latin' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Ubuntu:700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" type="text/css" href="/plugins/lightview/css/lightview/lightview.css"/>

        <script type="text/javascript" src="/assets/jscript/jquery-latest.min.js"></script>

        <!--<script class="rs-file" src="/plugins/royalslider/jquery-1.8.3.min.js"></script>-->
        <script type="text/javascript" src="/plugins/royalslider/jquery.royalslider.min.js"></script>
        <script type="text/javascript" src="/plugins/flexslider/jquery.flexslider-min.js"></script>
        
        
  <script src="/videoplayer/js/froogaloop.js" type="text/javascript"></script>
 
  <script src="/videoplayer/js/IScroll4Custom.js" type="text/javascript"></script>
 
  <script src='/videoplayer/js/THREEx.FullScreen.js'></script>
 
  <script src="/videoplayer/js/videoPlayer.js" type="text/javascript"></script>
 
  <script src="/videoplayer/js/Playlist.js" type="text/javascript"></script>