<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#banner_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-banner-data', 'banner') ?>",
        "aaSorting": [[ 1, "desc" ]],
        "aoColumns": [
            null,
            { sWidth: '200px' },
            { "bSortable": true, sWidth: '150px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#banner_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
});
</script>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-briefcase-2"></span>
                    <span><?php echo $this->translate('Banners') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-banner', 'banner') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">
                <table id="banner_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Visible on site') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>