<?php

/**
 * Guests_Model_Doctrine_PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Guests_Model_Doctrine_PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Guests_Model_Doctrine_PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Guests_Model_Doctrine_Post');
    }
    
    public function getPublishPostsQuery($id, $field = 'id') {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->andWhere('(a.publish = ?)', array(1))
                ;
        if(is_integer($id)) {
            $q->andWhere('a.' . $field . ' = ?', array($id));
        } elseif(is_array($id) && !empty($id)) {
            $q->andWhere('a.' . $field . ' IN ?', array($id));
        }
        return $q;
    }
    
    public function getLimitQuery($limit, Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('a');
            $q->addSelect('a.*');
        }
        $q->limit($limit);
        return $q;
    }
    
}