    <?php if(isset($this->tree)): ?>
    
        <?php foreach($this->tree as $item):
            
            ?>
        <li id="node<?php echo $item->getId() ?>" class="<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?> folder">
            <?php 
            if(strlen($item->getRoute())>0){
                if(!$slug=$item->Translation[$this->language]->slug): ?>
                    <a href="<?php echo $this->url(array(), $item->getRoute()); ?>"><?php echo $item->Translation[$this->language]['title']; ?></a>
                <?php else: ?>
                     <a href="<?php echo $this->url(array('slug' => $slug), $item->getRoute()); ?>"><?php echo mb_strtoupper($item->Translation[$this->language]['title'],'UTF-8'); ?></a>
                <?php endif; }
            else{ ?>
                    <a href="javascript:void(0)"><?php echo mb_strtoupper($item->Translation[$this->language]['title'],'UTF-8'); ?></a>
                <?php }
                ?>
       
        </li>
      
        <?php endforeach; ?>
    
    <?php elseif(isset($this->subtree)): ?>
    
        <?php foreach($this->subtree as $item): ?>
        <li id="node<?php echo $item->getId() ?>" class="<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?>"><a href="<?php echo $this->url(array(), $item->getRoute()); ?>"><?php echo $item->Translation[$this->language]['title'] ?></a>
            <?php if($item->getNode()->getChildren()): ?>
            <?php echo $this->partial('footer_main_subtree.phtml', 'menu', array('subtree' => $item->getNode()->getChildren(), 'parent' => $this->parent, 'language' => $this->language)) ?>
           <?php 
                  endif; ?>
        </li>
        <?php endforeach; ?>
        
    <?php endif; ?>
