<?php if(isset($this->tree)): ?>
<ul class="load-responsive" rel="Main Menu">
<?php elseif(isset($this->subtree)): ?>
<ul class=''>
<?php  endif; ?>

    <?php if(isset($this->tree)):?>
    
        <?php foreach($this->tree as $item):?>
        <li id="node<?php echo $item->getId() ?>" data-content="<?php echo $item->Translation[$this->language]->slug; ?>" class="big_dropdown menuItem <?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?>"><a href="<?php echo $this->url(array('slug' => $item->Translation[$this->language]->slug), $item->getRoute()); ?>"><?php echo $item->Translation[$this->language]['title'] ?></a>
            
        </li>
        <?php endforeach; ?>
    
    <?php elseif(isset($this->subtree)): ?>
    
        <?php foreach($this->subtree as $item): 
            $parent = $item->getNode()->getParent();
            ?>
        <li id="node<?php echo $item->getId() ?>"  class="big_dropdown subItem<?php if(isset($this->parent) && $this->parent->getId() == $item->getId()): ?>active<?php endif; ?>"><a href="<?php echo $this->url(array('slug' => $parent->Translation[$this->language]->slug), $item->getRoute()); ?>">><?php echo $item->Translation[$this->language]['title'] ?></a>
            
            <?php if($item->getNode()->getChildren()): ?>
            <?php echo $this->partial('menu_tree.phtml', 'menu', array('subtree' => $item->getNode()->getChildren(), 'parent' => $this->parent, 'language' => $this->language)) ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
        
    <?php endif; ?>
    
</ul>