<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
        <div class="box">
        
          <div class="content">
            <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">

                <div class="title">

                    <h4>
                        <span class="icon16 icomoon-icon-pencil"></span>
                         <span><?php echo $this->translate('Edit post') ?> napisany przez <?php echo $this->post->getName(); ?> </span>
                    </h4>

                </div>

                <?php echo $this->form->name; ?>
                <?php echo $this->form->city; ?>
                <?php echo $this->form->publish; ?>
                <?php echo $this->form->message; ?>
                <?php echo $this->form->id; ?>
                    
                <div class="form-actions">
                    <?php echo $this->form->submit ?>
                    <a href="<?php echo $this->adminUrl('list-post', 'guests') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
               </div>       
            </form>
          </div>
        </div>
    </div>
</div>