<?php

/**
 * Gallery_Model_Doctrine_GalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Gallery_Model_Doctrine_GalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Gallery_Model_Doctrine_GalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gallery_Model_Doctrine_Gallery');
    }
    
    public function getFullGalleryQuery() {
        $q = $this->createQuery('g')
                ->addSelect('g.*')
                ->addSelect('gt.*')
                ->addSelect('m.*')
                ->addSelect('mt.*')
                ->addSelect('pr.*')
                ->addSelect('p.*')
                ->leftJoin('g.Translation gt')
                ->leftJoin('g.Metatag m')
                ->leftJoin('m.Translation mt')
                ->leftJoin('g.PhotoRoot pr')
                ->leftJoin('g.Photos p')
                ;
        return $q;
    }
    
    public function getShortGalleryQuery() {
        $q = $this->createQuery('g')
                ->addSelect('g.*')
                ->addSelect('gt.*')
                ->addSelect('pr.*')
                ->addSelect('c.*')
                ->leftJoin('g.Translation gt')
                ->leftJoin('g.PhotoRoot pr')
                ->leftJoin('g.Category c')
                ;
        return $q;
    }
    
    
}