<?php

/**
 * Menu_Model_Doctrine_FooterItemTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Menu_Model_Doctrine_FooterItemTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Menu_Model_Doctrine_FooterItemTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Menu_Model_Doctrine_FooterItemTranslation');
    }
}