<!DOCTYPE html>
<html>

<?php echo $this->render('_head.phtml'); ?>

<body>
	<div class="wrapper sticky_footer">
    	<!-- HEADER BEGIN -->
        <header>
            <div id="header">
            	<section class="top">
                	<div class="inner">
                    	<div class="fl">
                        	<div class="block_top_menu">
                            	<ul>
                                    <!--<li class="current"><a href="/">Home</a></li>-->
                                    
                                    <li ><a href="/">Strona główna</a></li>
                                    <li><a href="<?php echo $this->url(array(),'domain-contact'); ?>">Kontakt</a></li>
                                </ul>
                            </div>
                        </div>
                        
                        <div class="fr">
                        	
                            
                            <div class="block_social_top">
                            	<ul>
                                	<li><a href="#" class="fb">Facebook</a></li>
                                    <li><a href="#" class="tw">Twitter</a></li>
                                    <li><a href="#" class="rss">RSS</a></li>
                                </ul>
                            </div>
                        </div>
                        
                    	<div class="clearboth"></div>
                    </div>
                </section>
                
            	<section class="bottom">
                	<div class="inner">
                    	<div id="logo_top"><a href="index.html"><img src="/assets/images/logo_top.png" alt="BusinessNews" title="BusinessNews"></a></div>
                        
                        <div class="block_today_date">
                        	<div class="num"><p id="num_top"></p></div>
                            <div class="other">
                            	<p class="month_year"><span id="month_top"></span>, <span id="year_top"></span></p>
                                <p id="day_top" class="day"></p>
                            </div>
                        </div>
                        
                        <div class="fr">
                        	<div class="block_languages">
                            	<div class="text"><p>Language:</p></div>
                                <ul>
                                	<li class="current"><a href="#" class="eng">English</a></li>
                                    <li><a href="#" class="french">French</a></li>
                                    <li><a href="#" class="ger">German</a></li>
                                </ul>
                                
                                <div class="clearboth"></div>
                            </div>
                            
                            <div class="block_search_top">
                            	<form action="#">
                                	<div class="field"><input type="text" class="w_def_text" title="Enter Your Email Addres"></div>
                                    <input type="submit" class="button" value="Search">
                                    
                                    <div class="clearboth"></div>
                                </form>
                            </div>
                        </div>
                        
                        <div class="clearboth"></div>
                    </div>
                </section>
                
                <section class="section_main_menu">
                	<div class="inner">
                            <?php echo $this->layout()->mainMenu; ?>           
                    </div>
                </section>
                
                <section class="section_big_dropdown">
                	<div class="inner">
                    	<div class="block_big_dropdown" data-menu="business">
                        	<div class="content">
                            	<div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_3.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Embarrassing hidden in the middleany thing</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_4.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Content of a page when looking.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="popular_posts">
                                	<div class="title"><p>Popular Posts</p></div>
                                    <ul>
                                    	<li><a href="blog_post.html"><span>11 July, 2012</span>Established fact that a reader.</a></li>
                                        <li><a href="blog_post_w_slider.html"><span>08 July, 2012</span>Editors now use as their default model text.</a></li>
                                        <li><a href="blog_post_w_video.html"><span>05 July, 2012</span>Embarrassing hidden in the middle.</a></li>
                                        <li><a href="blog_post.html"><span>01 July, 2012</span>Anything embarrassing hidden in the middl.</a></li>
                                    </ul>
                                </div>
                                <div class="line"></div>
                                
                                <div class="more">
                                	<div class="title"><p>More In Business</p></div>
                                    <ul>
                                    	<li><a href="#">Business</a></li>
                                        <li><a href="#">Money</a></li>
                                        <li><a href="#">Isnvestor Programs</a></li>
                                        <li><a href="#">Banks</a></li>
                                    </ul>
                                </div>
                                
                                <div class="clearboth"></div>
                            </div>
                        </div>
                        
                        <div class="block_big_dropdown" data-menu="technology">
                        	<div class="content">
                            	<div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_5.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Simply dummy text of the printing.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_6.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Internet tend to repeat predefined chunks.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="popular_posts">
                                	<div class="title"><p>Popular Posts</p></div>
                                    <ul>
                                    	<li><a href="blog_post.html"><span>11 July, 2012</span>Publishing packages and web page</a></li>
                                        <li><a href="blog_post_w_slider.html"><span>08 July, 2012</span>Generators on the Internet tend to repeat.</a></li>
                                        <li><a href="blog_post_w_video.html"><span>05 July, 2012</span>Anything embarrassing hidden in the middle.</a></li>
                                        <li><a href="blog_post.html"><span>01 July, 2012</span>Words which don't look even slightly.</a></li>
                                    </ul>
                                </div>
                                <div class="line"></div>
                                
                                <div class="more">
                                	<div class="title"><p>More In Tech</p></div>
                                    <ul>
                                    	<li><a href="#">Web Development</a></li>
                                        <li><a href="#">Programming</a></li>
                                        <li><a href="#">Techique</a></li>
                                        <li><a href="#">Cars</a></li>
                                    </ul>
                                </div>
                                
                                <div class="clearboth"></div>
                            </div>
                        </div>
                        
                    	<div class="block_big_dropdown" data-menu="education">
                        	<div class="content">
                            	<div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_1.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Many desktop packages and web page editors.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_2.jpg" alt=""></a>
                                    <p><a href="blog_post.html">There are many variations passages</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="popular_posts">
                                	<div class="title"><p>Popular Posts</p></div>
                                    <ul>
                                    	<li><a href="blog_post.html"><span>11 July, 2012</span>Many desktop publishing packages and web page</a></li>
                                        <li><a href="blog_post_w_slider.html"><span>08 July, 2012</span>Randomised words which don't look even.</a></li>
                                        <li><a href="blog_post_w_video.html"><span>05 July, 2012</span>Anything embarrassing hidden in the middle.</a></li>
                                        <li><a href="blog_post.html"><span>01 July, 2012</span>Established fact that a reader.</a></li>
                                    </ul>
                                </div>
                                <div class="line"></div>
                                
                                <div class="more">
                                	<div class="title"><p>More In Education</p></div>
                                    <ul>
                                    	<li><a href="#">High school</a></li>
                                        <li><a href="#">Univercity</a></li>
                                        <li><a href="#">College</a></li>
                                        <li><a href="#">Students</a></li>
                                    </ul>
                                </div>
                                
                                <div class="clearboth"></div>
                            </div>
                        </div>
                    </div>
              	</section>
                
            </div>
        </header>
    	<!-- HEADER END -->
        
        <!-- CONTENT BEGIN -->
        <div id="content" class="right_sidebar">
        	<div class="inner">
            	<div class="general_content">
                	<div class="main_content">
                    	
                        
                            <?php echo $this->layout()->content; ?>
                        
                    </div>
                    
                    <div class="sidebar">
                    	<div class="block_subscribes_sidebar">
                        	<div class="service">
                            	<a href="#" class="rss">
                                	<span class="num">11 234</span>
                                    <span class="people">Subscribers</span>
                                </a>
                            </div>
                            
                            <div class="service">
                            	<a href="#" class="tw">
                                	<span class="num">781</span>
                                    <span class="people">Followers</span>
                                </a>
                            </div>
                            
                            <div class="service">
                            	<a href="#" class="fb">
                                	<span class="num">341</span>
                                    <span class="people">Subscribers</span>
                                </a>
                            </div>
                        </div>
                        
                      <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_popular_posts">
                        	<h4>Popular Posts</h4>
                            
                        	<div class="article">
								<div class="pic">
									<a href="#" class="w_hover">
										<img src="/assets/images/pic_popular_post_1.jpg" alt="">
										<span></span>
									</a>
								</div>
                                        
								<div class="text">
									<p class="title"><a href="#">Packages and web page editors their default text.</a></p>
									<div class="date"><p>11 July, 2012</p></div>
                                    <div class="icons">
                                    	<ul>
                                        	<li><a href="#" class="views">41</a></li>
                                            <li><a href="#" class="comments">22</a></li>
                                        </ul>
                                    </div>
								</div>
							</div>
							<div class="line_3"></div>
                            
                            <div class="article">
								<div class="pic">
									<a href="#" class="w_hover">
										<img src="/assets/images/pic_popular_post_2.jpg" alt="">
										<span></span>
									</a>
								</div>
                                        
								<div class="text">
									<p class="title"><a href="#">Web page editors their default model text, and a search for.</a></p>
									<div class="date"><p>07 July, 2012</p></div>
                                    <div class="icons">
                                    	<ul>
                                        	<li><a href="#" class="views">24</a></li>
                                            <li><a href="#" class="comments">16</a></li>
                                        </ul>
                                    </div>
								</div>
							</div>
							<div class="line_3"></div>
                            
                            <div class="article">
								<div class="pic">
									<a href="#" class="w_hover">
										<img src="/assets/images/pic_popular_post_3.jpg" alt="">
										<span></span>
									</a>
								</div>
                                        
								<div class="text">
									<p class="title"><a href="#">Editors their default model text, and a search uncover.</a></p>
									<div class="date"><p>05 July, 2012</p></div>
                                    <div class="icons">
                                    	<ul>
                                        	<li><a href="#" class="views">33</a></li>
                                            <li><a href="#" class="comments">25</a></li>
                                        </ul>
                                    </div>
								</div>
							</div>
							<div class="line_2"></div>
                        </div>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_popular_stuff">
                        	<h4>Popular Video</h4>
                            
                            <div class="content">
                            	<a href="#" class="view_all">Show all video</a>
                            	<div class="media"><a href="http://www.youtube.com/watch?v=ySIvism2af8" class="general_pic_hover play no_fx" data-rel="prettyPhoto" title="Popular Video"><img src="/assets/images/pic_pop_video.jpg" alt=""></a></div>
                                <p><a href="blog_post_w_video.html">Publishing packages and web page editors their default model.</a> <img src="/assets/images/icon_video.gif" alt=""></p>
                                <p class="date">11 July, 2012</p>
                            </div>
                            
                            <div class="info">
                            	<ul>
                                	<li class="comments"><a href="#">115</a></li>
                                    <li class="views"><a href="#">220</a></li>
                                </ul>
                            </div>
                            
                            <div class="clearboth"></div>
                            
                            <div class="line_2"></div>
                        </div>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_calendar">
                        	<h4>Calendar</h4>
                            
                            <div class="calendar" id="calendar_sidebar">
                            </div>
                            
                            <script type="text/javascript">
								var today = new Date();
								var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
								$('#calendar_sidebar').DatePicker({
									flat : true,
									date : date,
									calendars : 1,
									starts : 1,
									locale : {
										days : ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
										daysShort : ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
										daysMin : ['S', 'M', 'T', 'W', 'T', 'F', 'S', 'S'],
										months : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
										monthsShort : ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
										weekMin : 'wk'
									}
								});
							</script>
                            
                            <div class="line_2"></div>
                        </div>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_twitter_widget">
                        	<h4>Twitter Widget</h4>
                            <div class="lnk_follow"><a href="#" target="_blank">Follow on Twitter</a></div>
                            
                            <div class="tweet">
                            	<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
								<script type="text/javascript" src="/assets/layout/plugins/tweet/tweet.widget.js"></script>
                                <script type="text/javascript">
                                    // ('YOUR USERNAME','NUMBER OF POSTS');
                                    AddTweet('Web_Visions',1);
                                </script>
                            </div>
                            
                            <div class="line_2"></div>
                        </div>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_popular_stuff">
                        	<h4>Popular Photo</h4>
                            
                            <div class="content">
                            	<a href="#" class="view_all">Show all photos</a>
                            	<div class="media"><a href="/assets/images/pic_pop_photo_big.jpg" class="general_pic_hover zoom no_fx" data-rel="prettyPhoto" title="Popular Photo"><img src="/assets/images/pic_pop_photo.jpg" alt=""></a></div>
                                <p><a href="blog_post_w_slider.html">Editors their default model text, and a search for will uncover many.</a> <img src="/assets/images/icon_photo.gif" alt=""></p>
                                <p class="date">11 July, 2012</p>
                            </div>
                            
                            <div class="info">
                            	<ul>
                                	<li class="comments"><a href="#">100</a></li>
                                    <li class="views"><a href="#">134</a></li>
                                </ul>
                            </div>
                            
                            <div class="clearboth"></div>
                            
                            <div class="line_2"></div>
                        </div>
                        
                      	<div class="separator" style="height:31px;"></div>
                        
                        <div class="block_newsletter">
                        	<h4>Newsletter</h4>
                            
                            <form action="#">
                            	<div class="field"><input type="text" class="w_def_text" title="Enter Your Email Addres"></div>
                                <input type="submit" class="button" value="Subscribe">
                                
                                <div class="clearboth"></div>
                            </form>
                        </div>
                        
                    </div>
                    
                	<div class="clearboth"></div>
                </div>
            </div>
        </div>
    	<!-- CONTENT END -->
        
        <!-- FOOTER BEGIN -->
        <footer>
            <div id="footer">
            	<section class="top">
                	<div class="inner">
                    	<div id="logo_bottom"><a href="index.html"><img src="/assets/images/logo_bottom.png" alt=""></a></div>
                        
                        <div class="block_to_top">
                        	<a href="#">BACK TO TOP</a>
                        </div>
                    </div>
                </section>
                
            	<section class="middle">
                	<div class="inner">
                    	<div class="line_1"></div>
                        
                        <div class="block_footer_widgets">
                        	<div class="column">
                            	<h3>Photos on flickr</h3>
                                
                                <div class="block_flickr_footer">
                                	<ul>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_1.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_2.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_3.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_4.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_5.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_6.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_7.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_8.png" alt=""></a></li>
                                    </ul>
                                </div>
                            </div>
                            
                            <div class="column">
                            	<h3>Tags</h3>
                                
                                <div class="block_tags">
                                	<ul>
                                    	<li><a href="#">Business</a></li>
                                        <li><a href="#">Science</a></li>
                                        <li><a href="#">conferece</a></li>
                                        <li><a href="#">Photo</a></li>
                                        <li><a href="#">education</a></li>
                                        <li><a href="#">AI</a></li>
                                        <li><a href="#">Sport</a></li>
                                        <li><a href="#">mobile</a></li>
                                        <li><a href="#">Technology</a></li>
                                        <li><a href="#">computer</a></li>
                                        <li><a href="#">Video</a></li>
                                        <li><a href="#">apple</a></li>
                                        <li><a href="#">news</a></li>
                                        <li><a href="#">Euro</a></li>
                                        <li><a href="#">Culture</a></li>
                                        <li><a href="#">interior</a></li>
                                        <li><a href="#">Midle east</a></li>
                                        <li><a href="#">Design</a></li>
                                        <li><a href="#">euro 2012</a></li>
                                        <li><a href="#">flowers</a></li>
                                    </ul>
                                </div>
                            </div>
                            
                            <div class="column">
                            	<h3>most read news</h3>
                                
                                <div class="block_most_read_news">
                                	<div class="article">
                                    	<div class="pic">
                                        	<a href="news_post.html" class="w_hover">
                                            	<img src="/assets/images/pic_most_read_1.png" alt="">
                                                <span></span>
                                            </a>
                                        </div>
                                        
                                        <div class="text">
                                        	<p class="title"><a href="news_post.html">Content of a page when randomised.</a></p>
                                            <p class="date">08 July, 2012</p>
                                        </div>
                                    </div>
                                    <div class="line_1"></div>
                                    
                                    <div class="article">
                                    	<div class="pic">
                                        	<a href="news_post.html" class="w_hover">
                                            	<img src="/assets/images/pic_most_read_2.png" alt="">
                                                <span></span>
                                            </a>
                                        </div>
                                        
                                        <div class="text">
                                        	<p class="title"><a href="news_post.html">Established fact that a will be distracted.</a></p>
                                            <p class="date">08 July, 2012</p>
                                        </div>
                                    </div>
                                    <div class="line_1"></div>
                                    
                                    <div class="article">
                                    	<div class="pic">
                                        	<a href="news_post.html" class="w_hover">
                                            	<img src="/assets/images/pic_most_read_3.png" alt="">
                                                <span></span>
                                            </a>
                                        </div>
                                        
                                        <div class="text">
                                        	<p class="title"><a href="news_post.html">Distracted by the readable content of a page.</a></p>
                                            <p class="date">08 July, 2012</p>
                                        </div>
                                    </div>
                                    <div class="line_1"></div>
                                    
                                </div>
                            </div>
                            
                            <div class="column">
                            	<h3>contact widget</h3>
                                
                                <div class="block_contact_footer">
                                	<form action="#">
                                    	<p class="text">Name:</p>
                                        <div class="field"><input type="text"></div>
                                        
                                        <p class="text">Email:</p>
                                        <div class="field"><input type="text"></div>
                                        
                                        <p class="text">Message:</p>
                                        <div class="textarea"><textarea cols="1" rows="1"></textarea></div>
                                        
                                        <div class="clear_form"><input type="reset" value="Clear form"></div>
                                        <div class="send"><input type="submit" class="general_button" value="Submit"></div>
                                        
                                        <div class="clearboth"></div>
                                    </form>
                                </div>
                            </div>
                            
                            <div class="clearboth"></div>
                        </div>
                    </div>
                </section>
                
            	<section class="bottom">
                	<div class="inner">
                    	<div class="line_1"></div>
                        
                        <div class="fr">
                        	<div class="block_menu_footer">
                            	<ul>
                                	<li><a href="business.html">Business</a></li>
                                    <li><a href="technology.html">Technology</a></li>
                                    <li><a href="education.html">Education</a></li>
                                    <li><a href="media.html">Media</a></li>
                                </ul>
                            </div>
                            
                            <div class="block_social_footer">
                            	<ul>
                                	<li><a href="#" class="fb">Facebook</a></li>
                                    <li><a href="#" class="tw">Twitter</a></li>
                                    <li><a href="#" class="rss">RSS</a></li>
                                </ul>
                            </div>
                        </div>
                        
                        <div class="block_copyrights"><p>&copy; 2011 Business Press. All rights reserved.</p></div>
                    </div>
                </section>
            </div>
        </footer>
        <!-- FOOTER END -->
    </div>
    
</body>

</html>