<!DOCTYPE html>
<html>

<?php echo $this->render('_head.phtml'); ?>

<body>
	<div class="wrapper sticky_footer">
    	<!-- HEADER BEGIN -->
        <header>
            <div id="header">
            	<section class="top">
                	<div class="inner">
                    	<div class="fl">
                        	<div class="block_top_menu">
                            	<ul>
                                    <!--<li class="current"><a href="/">Home</a></li>-->
                                    
                                    <li ><a href="/">Strona główna</a></li>
                                    <li><a href="<?php echo $this->url(array(),'domain-contact'); ?>">Kontakt</a></li>
                                </ul>
                            </div>
                        </div>
                        
                        <div class="fr">
                        	
                            
                            <div class="block_social_top">
                            	<ul>
                                	<li><a href="#" class="fb">Facebook</a></li>
                                    <li><a href="#" class="tw">Twitter</a></li>
                                    <li><a href="#" class="rss">RSS</a></li>
                                </ul>
                            </div>
                        </div>
                        
                    	<div class="clearboth"></div>
                    </div>
                </section>
                
            	<section class="bottom">
                	<div class="inner">
                    	<div id="logo_top"><a href="index.html"><img src="/assets/images/logo_top.png" alt="BusinessNews" title="BusinessNews"></a></div>
                        
                        <div class="block_today_date">
                        	<div class="num"><p id="num_top"></p></div>
                            <div class="other">
                            	<p class="month_year"><span id="month_top"></span>, <span id="year_top"></span></p>
                                <p id="day_top" class="day"></p>
                            </div>
                        </div>
                        
                        <div class="fr">
                        	<div class="block_languages">
                            	<div class="text"><p>Language:</p></div>
                                <ul>
                                	<li class="current"><a href="#" class="eng">English</a></li>
                                    <li><a href="#" class="french">French</a></li>
                                    <li><a href="#" class="ger">German</a></li>
                                </ul>
                                
                                <div class="clearboth"></div>
                            </div>
                            
                            <div class="block_search_top">
                            	<form action="#">
                                	<div class="field"><input type="text" class="w_def_text" title="Enter Your Email Addres"></div>
                                    <input type="submit" class="button" value="Search">
                                    
                                    <div class="clearboth"></div>
                                </form>
                            </div>
                        </div>
                        
                        <div class="clearboth"></div>
                    </div>
                </section>
                
                <section class="section_main_menu">
                	<div class="inner">
                            <?php echo $this->layout()->mainMenu; ?>
<!--                        	<ul>
								<li class="current_page_item"><a href="index.html">Home</a>
                                	
                                    <ul>
                                    	<li><a href="index.html">Home Page Style 1</a></li>
                                        <li><a href="home_style_2.html">Home Page Style 2</a></li>
                                    </ul>
                                </li>
							  	<li class="big_dropdown" data-content="business"><a href="business.html">Business</a></li>
							  	<li class="big_dropdown" data-content="technology"><a href="technology.html">Technology</a></li>
							  	<li class="big_dropdown" data-content="education"><a href="education.html">Education</a></li>
							  	<li><a href="media.html">Media</a>
                                	
                                    <ul>
                                    	<li><a href="media.html">Media</a></li>
                                        <li><a href="media_item.html">Media Item Page</a></li>
                                    </ul>
                                </li>
							  	<li><a href="#">Pages</a>
                                	
                                    <ul>
                                    	<li><a href="about.html">About Us</a></li>
                                        <li><a href="about_author.html">About Author Page</a></li>
                                        <li><a href="contact.html">Contact Us</a></li>
                                        <li><a href="registration.html">Registration Page</a></li>
                                        <li><a href="main_news.html">Main News Page</a></li>
                                        <li><a href="news_post_w_slider.html">News Post With Slider</a></li>
                                        <li><a href="news_post_w_video.html">News Post With Video</a></li>
                                    </ul>
                                </li>
							  	<li><a href="blog.html">Blog</a>
                                	
                                    <ul>
                                    	<li><a href="blog.html">Our Blog Style 1</a></li>
                                        <li><a href="blog_style_2.html">Our Blog Style 2</a></li>
                                        <li><a href="blog_post.html">Blog Post Page</a></li>
                                        <li><a href="blog_post_w_slider.html">Post With Slider</a></li>
                                        <li><a href="blog_post_w_video.html">Post With Video</a></li>
                                    </ul>
                                </li>
		  		  		  		<li><a href="typography.html">Shortcodes</a>
                                	
                                    <ul>
                                    	<li><a href="accordion.html">Accordeon</a></li>
                                        <li><a href="blockquote.html">Blockquote</a></li>
                                        <li><a href="table.html">Table</a></li>
                                        <li><a href="columns.html">Columns</a></li>
                                        <li><a href="pricing_table.html">Pricing Table</a></li>
                                        <li><a href="testimonials.html">Testimonials</a></li>
                                        <li><a href="boxes.html">Info Boxes</a></li>
                                        <li><a href="dropcaps.html">Dropcaps</a></li>
                                        <li><a href="tabs.html">Tabs</a></li>
                                        <li><a href="lists.html">List Slyle</a></li>
                                        <li><a href="buttons.html">Buttons</a></li>
                                        <li><a href="video.html">Video</a></li>
                                        <li><a href="typography.html">Typography</a></li>
                                    </ul>
								</li>
						  </ul>-->
                    </div>
                </section>
                
                <section class="section_big_dropdown">
                	<div class="inner">
                    	<div class="block_big_dropdown" data-menu="business">
                        	<div class="content">
                            	<div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_3.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Embarrassing hidden in the middleany thing</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_4.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Content of a page when looking.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="popular_posts">
                                	<div class="title"><p>Popular Posts</p></div>
                                    <ul>
                                    	<li><a href="blog_post.html"><span>11 July, 2012</span>Established fact that a reader.</a></li>
                                        <li><a href="blog_post_w_slider.html"><span>08 July, 2012</span>Editors now use as their default model text.</a></li>
                                        <li><a href="blog_post_w_video.html"><span>05 July, 2012</span>Embarrassing hidden in the middle.</a></li>
                                        <li><a href="blog_post.html"><span>01 July, 2012</span>Anything embarrassing hidden in the middl.</a></li>
                                    </ul>
                                </div>
                                <div class="line"></div>
                                
                                <div class="more">
                                	<div class="title"><p>More In Business</p></div>
                                    <ul>
                                    	<li><a href="#">Business</a></li>
                                        <li><a href="#">Money</a></li>
                                        <li><a href="#">Isnvestor Programs</a></li>
                                        <li><a href="#">Banks</a></li>
                                    </ul>
                                </div>
                                
                                <div class="clearboth"></div>
                            </div>
                        </div>
                        
                        <div class="block_big_dropdown" data-menu="technology">
                        	<div class="content">
                            	<div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_5.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Simply dummy text of the printing.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_6.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Internet tend to repeat predefined chunks.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="popular_posts">
                                	<div class="title"><p>Popular Posts</p></div>
                                    <ul>
                                    	<li><a href="blog_post.html"><span>11 July, 2012</span>Publishing packages and web page</a></li>
                                        <li><a href="blog_post_w_slider.html"><span>08 July, 2012</span>Generators on the Internet tend to repeat.</a></li>
                                        <li><a href="blog_post_w_video.html"><span>05 July, 2012</span>Anything embarrassing hidden in the middle.</a></li>
                                        <li><a href="blog_post.html"><span>01 July, 2012</span>Words which don't look even slightly.</a></li>
                                    </ul>
                                </div>
                                <div class="line"></div>
                                
                                <div class="more">
                                	<div class="title"><p>More In Tech</p></div>
                                    <ul>
                                    	<li><a href="#">Web Development</a></li>
                                        <li><a href="#">Programming</a></li>
                                        <li><a href="#">Techique</a></li>
                                        <li><a href="#">Cars</a></li>
                                    </ul>
                                </div>
                                
                                <div class="clearboth"></div>
                            </div>
                        </div>
                        
                    	<div class="block_big_dropdown" data-menu="education">
                        	<div class="content">
                            	<div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_1.jpg" alt=""></a>
                                    <p><a href="blog_post.html">Many desktop packages and web page editors.</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="image">
                                	<a href="blog_post.html" class="pic"><img src="/assets/images/pic_big_drop_2.jpg" alt=""></a>
                                    <p><a href="blog_post.html">There are many variations passages</a></p>
                                </div>
                                <div class="line"></div>
                                
                                <div class="popular_posts">
                                	<div class="title"><p>Popular Posts</p></div>
                                    <ul>
                                    	<li><a href="blog_post.html"><span>11 July, 2012</span>Many desktop publishing packages and web page</a></li>
                                        <li><a href="blog_post_w_slider.html"><span>08 July, 2012</span>Randomised words which don't look even.</a></li>
                                        <li><a href="blog_post_w_video.html"><span>05 July, 2012</span>Anything embarrassing hidden in the middle.</a></li>
                                        <li><a href="blog_post.html"><span>01 July, 2012</span>Established fact that a reader.</a></li>
                                    </ul>
                                </div>
                                <div class="line"></div>
                                
                                <div class="more">
                                	<div class="title"><p>More In Education</p></div>
                                    <ul>
                                    	<li><a href="#">High school</a></li>
                                        <li><a href="#">Univercity</a></li>
                                        <li><a href="#">College</a></li>
                                        <li><a href="#">Students</a></li>
                                    </ul>
                                </div>
                                
                                <div class="clearboth"></div>
                            </div>
                        </div>
                    </div>
              	</section>
                
            </div>
        </header>
    	<!-- HEADER END -->
        
        <!-- CONTENT BEGIN -->
        <div id="content" class="right_sidebar">
        	<div class="inner">
            	<div class="general_content">
                	<div class="main_content">
                    	
                            <?php echo $this->layout()->specialTopic; ?>
                            
                            <?php echo $this->layout()->lastNewsSlider; ?>
                        
                            
                            <?php echo $this->layout()->lastNewsTop; ?>
                        
                        <div class="line_3" style="margin:13px 0px 35px;"></div>
                        
                        
                            <?php echo $this->layout()->lastCategoriesNews; ?>
                        
                        <div class="line_2" style="margin:24px 0px 35px;"></div>
                    
                    </div>
                    
                    <div class="sidebar">
                    	<div class="block_subscribes_sidebar">
                        	<div class="service">
                            	<a href="#" class="rss">
                                	<span class="num">11 234</span>
                                    <span class="people">Subscribers</span>
                                </a>
                            </div>
                            
                            <div class="service">
                            	<a href="#" class="tw">
                                	<span class="num">781</span>
                                    <span class="people">Followers</span>
                                </a>
                            </div>
                            
                            <div class="service">
                            	<a href="#" class="fb">
                                	<span class="num">341</span>
                                    <span class="people">Subscribers</span>
                                </a>
                            </div>
                        </div>
                        
                      <div class="separator" style="height:31px;"></div>
                        
                        
                            <?php echo $this->layout()->popularNews; ?>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <?php echo $this->layout()->randomPerson; ?>
                                               
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_calendar">
                        	<h4>Najbliższe wydarzenia w regionie</h4>
                            
                                <?php echo $this->layout()->calendar; ?>
<!--                            <div class="calendar" id="calendar_sidebar">
                            </div>-->
                            
<!--                            <script type="text/javascript">
								var today = new Date();
								var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
								$('#calendar_sidebar').DatePicker({
									flat : true,
									date : date,
									calendars : 1,
									starts : 1,
									locale : {
										days : ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota', 'Niedziela'],
										daysShort : ['Nie', 'Pon', 'Wto', 'Śro', 'Czw', 'Pią', 'Sob', 'Nie'],
										daysMin : ['N', 'P', 'W', 'Ś', 'C', 'P', 'S', 'N'],
										months : ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Siepień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
										monthsShort : ['Sty', 'Lu', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],
										weekMin : 'wk'
									}
								});
							</script>-->
                            
                            <div class="line_2"></div>
                        </div>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_twitter_widget">
                        	<h4>Twitter Widget</h4>
                            <div class="lnk_follow"><a href="#" target="_blank">Follow on Twitter</a></div>
                            
                            <div class="tweet">
                            	<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
								<script type="text/javascript" src="/assets/layout/plugins/tweet/tweet.widget.js"></script>
                                <script type="text/javascript">
                                    // ('YOUR USERNAME','NUMBER OF POSTS');
                                    AddTweet('Web_Visions',1);
                                </script>
                            </div>
                            
                            <div class="line_2"></div>
                        </div>
                        
                        <div class="separator" style="height:31px;"></div>
                        
                        <div class="block_popular_stuff">
                        	<h4>Popular Photo</h4>
                            
                            <div class="content">
                            	<a href="#" class="view_all">Show all photos</a>
                            	<div class="media"><a href="/assets/images/pic_pop_photo_big.jpg" class="general_pic_hover zoom no_fx" data-rel="prettyPhoto" title="Popular Photo"><img src="/assets/images/pic_pop_photo.jpg" alt=""></a></div>
                                <p><a href="blog_post_w_slider.html">Editors their default model text, and a search for will uncover many.</a> <img src="/assets/images/icon_photo.gif" alt=""></p>
                                <p class="date">11 July, 2012</p>
                            </div>
                            
                            <div class="info">
                            	<ul>
                                	<li class="comments"><a href="#">100</a></li>
                                    <li class="views"><a href="#">134</a></li>
                                </ul>
                            </div>
                            
                            <div class="clearboth"></div>
                            
                            <div class="line_2"></div>
                        </div>
                        
                      	<div class="separator" style="height:31px;"></div>
                        
                        <div class="block_newsletter">
                        	<h4>Newsletter</h4>
                            
                            <form action="#">
                            	<div class="field"><input type="text" class="w_def_text" title="Enter Your Email Addres"></div>
                                <input type="submit" class="button" value="Subscribe">
                                
                                <div class="clearboth"></div>
                            </form>
                        </div>
                        
                    </div>
                    
                	<div class="clearboth"></div>
                </div>
            </div>
        </div>
    	<!-- CONTENT END -->
        
        <!-- FOOTER BEGIN -->
        <footer>
            <div id="footer">
            	<section class="top">
                	<div class="inner">
                    	<div id="logo_bottom"><a href="index.html"><img src="/assets/images/logo_bottom.png" alt=""></a></div>
                        
                        <div class="block_to_top">
                        	<a href="#">BACK TO TOP</a>
                        </div>
                    </div>
                </section>
                
            	<section class="middle">
                	<div class="inner">
                    	<div class="line_1"></div>
                        
                        <div class="block_footer_widgets">
                        	<div class="column">
                            	<h3>Photos on flickr</h3>
                                
                                <div class="block_flickr_footer">
                                	<ul>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_1.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_2.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_3.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_4.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_5.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_6.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_7.png" alt=""></a></li>
                                        <li><a href="http://www.flickr.com/" target="_blank"><img src="/assets/images/pic_flickr_8.png" alt=""></a></li>
                                    </ul>
                                </div>
                            </div>
                            
                            <div class="column">
                            	<h3>Tags</h3>
                                
                                <div class="block_tags">
                                	<ul>
                                    	<li><a href="#">Business</a></li>
                                        <li><a href="#">Science</a></li>
                                        <li><a href="#">conferece</a></li>
                                        <li><a href="#">Photo</a></li>
                                        <li><a href="#">education</a></li>
                                        <li><a href="#">AI</a></li>
                                        <li><a href="#">Sport</a></li>
                                        <li><a href="#">mobile</a></li>
                                        <li><a href="#">Technology</a></li>
                                        <li><a href="#">computer</a></li>
                                        <li><a href="#">Video</a></li>
                                        <li><a href="#">apple</a></li>
                                        <li><a href="#">news</a></li>
                                        <li><a href="#">Euro</a></li>
                                        <li><a href="#">Culture</a></li>
                                        <li><a href="#">interior</a></li>
                                        <li><a href="#">Midle east</a></li>
                                        <li><a href="#">Design</a></li>
                                        <li><a href="#">euro 2012</a></li>
                                        <li><a href="#">flowers</a></li>
                                    </ul>
                                </div>
                            </div>
                            
                            <div class="column">
                            	<h3>most read news</h3>
                                
                                <div class="block_most_read_news">
                                	<div class="article">
                                    	<div class="pic">
                                        	<a href="news_post.html" class="w_hover">
                                            	<img src="/assets/images/pic_most_read_1.png" alt="">
                                                <span></span>
                                            </a>
                                        </div>
                                        
                                        <div class="text">
                                        	<p class="title"><a href="news_post.html">Content of a page when randomised.</a></p>
                                            <p class="date">08 July, 2012</p>
                                        </div>
                                    </div>
                                    <div class="line_1"></div>
                                    
                                    <div class="article">
                                    	<div class="pic">
                                        	<a href="news_post.html" class="w_hover">
                                            	<img src="/assets/images/pic_most_read_2.png" alt="">
                                                <span></span>
                                            </a>
                                        </div>
                                        
                                        <div class="text">
                                        	<p class="title"><a href="news_post.html">Established fact that a will be distracted.</a></p>
                                            <p class="date">08 July, 2012</p>
                                        </div>
                                    </div>
                                    <div class="line_1"></div>
                                    
                                    <div class="article">
                                    	<div class="pic">
                                        	<a href="news_post.html" class="w_hover">
                                            	<img src="/assets/images/pic_most_read_3.png" alt="">
                                                <span></span>
                                            </a>
                                        </div>
                                        
                                        <div class="text">
                                        	<p class="title"><a href="news_post.html">Distracted by the readable content of a page.</a></p>
                                            <p class="date">08 July, 2012</p>
                                        </div>
                                    </div>
                                    <div class="line_1"></div>
                                    
                                </div>
                            </div>
                            
                            <div class="column">
                            	<h3>contact widget</h3>
                                
                                <div class="block_contact_footer">
                                	<form action="#">
                                    	<p class="text">Name:</p>
                                        <div class="field"><input type="text"></div>
                                        
                                        <p class="text">Email:</p>
                                        <div class="field"><input type="text"></div>
                                        
                                        <p class="text">Message:</p>
                                        <div class="textarea"><textarea cols="1" rows="1"></textarea></div>
                                        
                                        <div class="clear_form"><input type="reset" value="Clear form"></div>
                                        <div class="send"><input type="submit" class="general_button" value="Submit"></div>
                                        
                                        <div class="clearboth"></div>
                                    </form>
                                </div>
                            </div>
                            
                            <div class="clearboth"></div>
                        </div>
                    </div>
                </section>
                
            	<section class="bottom">
                	<div class="inner">
                    	<div class="line_1"></div>
                        
                        <div class="fr">
                        	<div class="block_menu_footer">
                            	<ul>
                                	<li><a href="business.html">Business</a></li>
                                    <li><a href="technology.html">Technology</a></li>
                                    <li><a href="education.html">Education</a></li>
                                    <li><a href="media.html">Media</a></li>
                                </ul>
                            </div>
                            
                            <div class="block_social_footer">
                            	<ul>
                                	<li><a href="#" class="fb">Facebook</a></li>
                                    <li><a href="#" class="tw">Twitter</a></li>
                                    <li><a href="#" class="rss">RSS</a></li>
                                </ul>
                            </div>
                        </div>
                        
                        <div class="block_copyrights"><p>&copy; 2011 Business Press. All rights reserved.</p></div>
                    </div>
                </section>
            </div>
        </footer>
        <!-- FOOTER END -->
    </div>
    
</body>

</html>