<!DOCTYPE html> 
<html>
<head>
    <?php echo $this->partial('_head.phtml') ?>
    <style>
        .content{
    margin-top:0px;
}
    </style>
</head>

<body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1&appId=530955950330860";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <div class="root">
	<header class="h10 sticky-enabled no-topbar">
		
                <?php echo $this->render('_header.phtml') ?>
            
		<?php echo $this->layout()->topMenu; ?>
		
		
	</header>
        <section class="categoryHeader">
           <h2>
            <?php
                    echo $this->translate('New products');
            ?>
            </h2>
            <hr />
        </section> 
	<!-- .container_12 start -->
            <div class="container_12">

                <!-- .rs-wrapper start -->
                <div class="rs-wrapper">
                    <?php echo $this->layout()->slider_collection; ?>
                </div><!-- .rs-wrapper end -->

                
                <div class="clearfix"></div>

            </div>
            <!-- .container_12 end -->

	<section class="content reverse">
		<section class="main">
			<?php echo $this->layout()->content; ?>
		</section>
		
            
		<a href="#" class="go-top">Go to top of page</a>
	</section>

	 <?php echo $this->layout()->footer; ?>
    </div>
</body>

</html>