<script type="text/javascript">
    $(document).ready(function(){
        $( "#dimension_width" ).slider({
                range: "min",
                value: 100,
                min: 0,
                max: 200,
                step: 1,
                slide: function( event, ui ) {
                        $( "#width" ).val(ui.value+" cm");
                }
        });
        $( "#width" ).val($( "#dimension_width" ).slider( "value" ) + " cm");

        $( "#dimension_height" ).slider({
                range: "min",
                value: 150,
                min: 0,
                max: 300,
                step: 1,
                slide: function( event, ui ) {
                        $( "#height" ).val(ui.value+" cm");
                }
        });
        $( "#height" ).val($( "#dimension_height" ).slider( "value" ) + " cm");
});
</script>
<div class="span6">
        
    <div class="box">

        <div class="title">

            <h4>
                <span class="icon16 icomoon-icon-rulers"></span>
                <span><?php echo $this->translate('Add new dimension') ?></span>
           </h4> 
        </div>

        <div class="content clearfix">
            <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                <?php echo $this->form->id; ?>

                <?php echo $this->form->width->getLabel(); ?>
                <div id="dimension_width" class="slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"><div class="ui-slider-range ui-widget-header ui-slider-range-min" style="width: 0;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#"></a></div>
                <?php echo $this->form->width->removeDecorator('Label'); ?>

                <?php echo $this->form->height->getLabel(); ?>
                <div id="dimension_height" class="slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"><div class="ui-slider-range ui-widget-header ui-slider-range-min" style="width: 0;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#"></a></div>
                <?php echo $this->form->height->removeDecorator('Label');; ?>


                <div class="form-actions">
                    <?php echo $this->form->submit ?>
                    <a href="<?php echo $this->adminUrl('list-producer', 'product') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
               </div>

            </form>

        </div>

    </div><!-- End .box -->

</div>