<script type="text/javascript">
$(document).ready(function() {
 
   $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
    
    $('#explorer2').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
//   
    $("#itemContainer").delegate("#add-photo", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
       // $("#explorer").modal({
        //    overlayCss: {"background": "black"}
       // });
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-collection-photo', 'product') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#id").val(resp.id);
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
              //  $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
        
        var elf = $('#elfinder2').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-collection-main-photo', 'product') ?>/id/"+$('#id').val(),
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_con").html(resp.body);
                            $("#itemCon").trigger('update');
                        }
                    }
                });

                $('#explorer2').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer2').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .delete", "click", function(e) {
            e.preventDefault();
            $.ajax({
                type: "post",
                dataType: "json",
                url: "<?php echo $this->adminUrl('remove-collection-main-photo', 'product') ?>/id/"+$('#id').val(),
                data: data,
                success: function(resp) {
                    if(resp.status == "success") {
                        $("#main_photo_con").html(resp.body);
                        $("#itemCon").trigger('update');
                    }
                }
            });
     }); 
     
});
</script>

<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
        <div class="box">
            
           <div class="title">

                    <h4>
                        <span class="icon16 icomoon-icon-pencil"></span>
                        <span><?php echo $this->translate('Edit') ?> <?php echo $this->collection->Translation[$this->adminLanguage]['name']; ?></span>
                    </h4>

          </div>
        
          <div class="content">
            <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">

                <div class="page-header">
                    <h4><?php echo $this->translate('Translations') ?></h4>
                </div>
                
                <ul id="myTab" class="nav nav-tabs pattern">
                    <li class="dropdown">
                        <?php foreach($this->languages as $key => $language): ?>
                            <li class="<?php if($language == $this->adminLanguage->getId()): ?>active<?php endif; ?>"><a href="#dropdown<?php echo $key + 1 ?>" data-toggle="tab"><?php echo $language ?></a></li>
                        <?php endforeach; ?>
                    </li>
                </ul>
                
                <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">

                                <?php if($this->form->translations->getSubForm($language)): ?>
                                    <?php echo $this->form->translations->getSubForm($language)->name ?>
                                    <?php echo $this->form->translations->getSubForm($language)->description ?>
                                <?php endif; ?>

                                <div class="title" style ="margin-top: 30px;">
                                    <h4>
                                        <span class="icon16  icomoon-icon-tag-2"></span>
                                        <span><?php echo $this->translate('Metatags') ?></span>
                                    </h4>
                                </div>
                                <div class="content clearfix">
                                    <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                    <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                    <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                                </div>

                            </div>
                            <?php endforeach; ?>
                   </div>
                
                   <?php echo $this->form->discount_id->setAttribs(array('class' => 'nostyle')) ;
                           echo $this->form->promoted;
                           ?>
                
                      <div class="page-header">
                         <h4><?php echo $this->translate('Main photo') ?></h4>
                    </div>  
                    <div id="itemCon">
                        <ul id="main_photo_con" class="galleryView center">
                            <li class="pull-left">
                                <?php if($this->collection->get('PhotoRoot')->getOffset()): ?>
                                <a id="main_photo" href="/media/photos/<?php echo $this->collection->get('PhotoRoot')->getOffset() ?>/<?php echo $this->collection->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->collection->get('PhotoRoot')->getTitle() ?>">
                                    <img src="/media/photos/<?php echo $this->collection->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->collection->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->collection->get('PhotoRoot')->getOffset() ?>/<?php echo $this->collection->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->collection->get('PhotoRoot')->getTitle() ?>">
                                </a>
                                <?php else: ?>
                                <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                    <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                </a>
                                <?php endif; ?>
                                <div class="actionBtn">
                                    <a href="<?php echo $this->adminUrl('edit-collection-main-photo', 'product', array('collection-id' => $this->collection->getId(), 'id' => $this->collection->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                    <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                    <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                </div>
                            </li>
                        </ul>
                    </div> 
                    
                    <div class="clearfix"></div>
                    <div class="page-header">
                         <h4><?php echo $this->translate('Gallery View') ?></h4>
                    </div>                  
                      <div id="itemContainer">           
                        <button href="#" id="add-photo" style="width: 120px;"><?php echo $this->translate('Add photo') ?></button>
                        <ul id="main_photo_container" class="galleryView center">                           
                                <?php echo $this->partial('admin/collection-main-photo.phtml', 'product', array('photos' => $this->collectionPhotos, 'collection' => $this->collection)) ?>
                        </ul>
                      </div>
                          
                <?php echo $this->form->id ?>
                    
                <div class="form-actions">
                    <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-collection', 'product'); ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                   
               </div>       
            </form>
          </div>
        </div>
    </div>
</div>
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
<div id="explorer2" class="dialog"><div id="elfinder2"></div></div>