<script type="text/javascript">
$(document).ready(function() {
 
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
    
    $('#explorer2').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
    });
//   
    $("#itemContainer").delegate("#add-photo", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
       // $("#explorer").modal({
        //    overlayCss: {"background": "black"}
       // });
        
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-product-photo', 'product') ?>/id/"+ <?php echo $this->id; ?>,
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#id").val(resp.id);
                            $("#main_photo_container").html(resp.body);
                            $("#itemContainer").trigger('update');
                        }
                    }
                });

                $('#explorer').dialog('close');
              //  $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .add", "click", function(e) {
        e.preventDefault();
        $("#explorer-content").show();
        
        var elf = $('#elfinder2').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-product-main-photo', 'product') ?>/id/"+<?php echo $this->id; ?>,
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#main_photo_con").html(resp.body);
                            $("#itemCon").trigger('update');
                        }
                    }
                });

                $('#explorer2').dialog('close');
//                $.modal.close();
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
//                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer2').dialog('open');
    });
    
    $("#itemCon").delegate(".actionBtn .delete", "click", function(e) {
            e.preventDefault();
            $.ajax({
                type: "post",
                dataType: "json",
                url: "<?php echo $this->adminUrl('remove-product-main-photo', 'product') ?>/id/"+<?php echo $this->id; ?>,
                data: data,
                success: function(resp) {
                    if(resp.status == "success") {
                        $("#main_photo_con").html(resp.body);
                        $("#itemCon").trigger('update');
                    }
                }
            });
     }); 
     
     
     $("#category_tree_selection").dynatree({
        checkbox: true,  
        autoCollapse: true,
        minExpandLevel: 2
     });
    
     $("#category_tree_selection").click(function(){
        
        var selectedNodes = $("#category_tree_selection").dynatree("getTree").getSelectedNodes(); 

        var selectedKeys = $.map(selectedNodes, function(node){ 
            return node.data.key; 
        }); 
        
        var ids = new Array();
        for(var x=0; x<selectedKeys.length; x++){
            var id = selectedKeys[x];
            ids[x] = id.replace(/^node/, "");
        }
        
        $("#category_id option").each(function(i, elem) {
            $(elem).attr("selected", false);
        });
       
    
        for(id in ids) {
            var option = $("#category_id option[value="+ids[id]+"]");
            if(option) {
                $(option).attr("selected", "selected");
            }
        }   
     });
     
     
     var uploader = new qq.FileUploaderBasic({
        button: document.getElementById('add_attachment'),
        action: "<?php echo $this->adminUrl('add-attachment', 'product') ?>/id/"+<?php echo $this->id; ?>,
        inputName: "file",
        forceMultiple: true,
        autoUpload: true,
        debug: true,
        forceMultipart: true,
        sizeLimit: 10520000,
        
        onSubmit: function (id, fileName) {
            $('#add_attachment').find('.qq-upload-file').each(function () {
                if ($(this).text() == fileName) {
                    return false;
                return true;
                }
            });
        },
        onComplete: function(){
            $("#attachment_table").trigger("update");
        }
     });
//     
     $("#attachment_table").delegate(".remove2", "click", function(e) {
            e.preventDefault();
            var link = $(this).attr("href");
            if(confirm("Czy na pewno chcesz usunąć?")) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: link,
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            //$("#main_photo_con").html(resp.body);
                            $("#attachment_table").trigger('update');
                        }
                    }
                });
            }
     });  
     
     var oTable = $("#attachment_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-attachment-data', 'product', array('id' => $this->product->getId())) ?>",
        "aaSorting": [[ 1, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
//    
    $("#attachment_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
////    
////    
   

    
    $(document).on('click', '#newpromotion', function(){
        var value = $(this).attr('checked');
        if(value)
            $(this).parent().find('#newpromotionprice').attr('readonly', false);
        else
            $(this).parent().find('#newpromotionprice').attr('readonly', true);
    });
    
    $(document).on('click', '.add_price', function(e){
        e.preventDefault();
        var link = $(this).attr("href");
        
        var mostfrequentlypurchased = 0;
        if($(this).parent().parent().find('#mostfrequentlypurchased').attr('checked')){
            mostfrequentlypurchased = 1;
        }
        var lastnew = 0;
        if($(this).parent().parent().find('#lastnew').attr('checked')){
            lastnew = 1;
        }
        var promoted = 0;
        if($(this).parent().parent().find('#newpromoted').attr('checked')){
            promoted = 1;
        }
        var promotion = 0;
        if($(this).parent().parent().find('#newpromotion').attr('checked')){
            promotion = 1;
        }
        var promotionprice = 0;
        if(newPromotionPrice = $(this).parent().parent().find('#newpromotionprice').attr('value')){
            promotionprice = newPromotionPrice;
        }
        var price = 0;
        if(newPrice = $(this).parent().parent().find('#newprice').attr('value')){
            price = newPrice;
        }
        var availability = 1;
        if(newAvailability = $(this).parent().parent().find('#newavailability').attr('value')){
            availability = newAvailability;
        }
        var dimension = $(this).parent().parent().find('#dimension').attr('value');
        
        var discount = $(this).parent().parent().find('#discount').attr('value');
        
        var id = $(this).attr('value');
        
        var data = {
            id: id,
            dimension_id: dimension,
            price: price,
            availability: availability,
            product_id: <?php echo $this->product['id'] ?>,
            promoted: promoted,
            promotion: promotion,
            promotion_price: promotionprice,
            new: lastnew,
            most_frequently_purchased: mostfrequentlypurchased,
            discount_id: discount
        }
        $.ajax({
            type: "post",
            dataType: "json",
            url: link,
            data: data,
            context: this,
            success: function(resp) {
                if(resp.added == 1 || resp.edited == 1) {
                    $("#prices_and_dimensions").trigger("update");
                }else{
                    if(error = resp.error){
                        alert(error);
                    }
                }
            }
        });
    });
    
    $('#promotion').each(function(){
        var value = $(this).attr('checked');
        if(value){
            $('#promotion_price').attr('readonly', false);
        }else{
            $('#promotion_price').attr('readonly', true);
        }
    });
     
     $("#dimensions").each(function(){
        if($(this).attr('checked')){
            $("#price").closest('.form-row.row-fluid').hide();
            $("#availability").closest('.form-row.row-fluid').hide();
            $("#promoted").closest('.form-row.row-fluid').hide();
            $("#new").closest('.form-row.row-fluid').hide();
            $("#most_frequently_purchased").closest('.form-row.row-fluid').hide();
            $("#discount_id").closest('.form-row.row-fluid').hide();
            $("#promotion").closest('.form-row.row-fluid').hide();
            $("#promotion_price").closest('.form-row.row-fluid').hide();
        }else{
            $('#prices_and_dimensions').parent().hide();
        }
    });
    
    $("#dimensions").parent().click( function(){
        if($("#dimensions").attr('checked')){
            $("#price").closest('.form-row.row-fluid').slideUp();
            $("#availability").closest('.form-row.row-fluid').slideUp();
            $("#promoted").closest('.form-row.row-fluid').slideUp();
            $("#new").closest('.form-row.row-fluid').slideUp();
            $("#most_frequently_purchased").closest('.form-row.row-fluid').slideUp();
            $("#discount_id").closest('.form-row.row-fluid').slideUp();
            $('#promotion').closest('.form-row.row-fluid').slideUp();
            $('#promotion_price').closest('.form-row.row-fluid').slideUp();
            $('#prices_and_dimensions').parent().parent().slideDown();
        }else{
            $("#price").closest('.form-row.row-fluid').slideDown();
            $("#availability").closest('.form-row.row-fluid').slideDown();
            $("#promoted").closest('.form-row.row-fluid').slideDown();
            $("#new").closest('.form-row.row-fluid').slideDown();
            $("#most_frequently_purchased").closest('.form-row.row-fluid').slideDown();
            $("#discount_id").closest('.form-row.row-fluid').slideDown();
            $('#promotion').closest('.form-row.row-fluid').slideDown();
            $('#promotion_price').closest('.form-row.row-fluid').slideDown();
            $('#prices_and_dimensions').parent().parent().slideUp();
        }
     });
     
});
//
//
//
    $(document).on('click', '.remove_dimension_price', function(e) {
        if(!confirm("<?php echo $this->translate('Do you really want to delete item?') ?>")) {
            e.preventDefault();
            return false;
        }
        e.preventDefault();
        var data = {
            id: $(this).attr('value')
        }
        var link = $(this).attr("href");
            $.ajax({
                type: "post",
                dataType: "json",
                url: "<?php echo $this->adminUrl('remove-dimension-price', 'product'); ?>",
                data: data,
                context: this,
                success: function(resp) {
                    if(resp.deleted == 1) {
                        $("#prices_and_dimensions").trigger("update");
                    }
                }
            });
    });
//
    $(document).on('click', '.edit_dimension_price', function(e){
        e.preventDefault();
        
        var id = $(this).attr('value');
        
        var data = {
            query: true,
            id: id
        }
        
        $.ajax({
            type: "post",
            dataType: "json",
            url: "<?php //echo $this->adminUrl('edit-dimension-price', 'product'); ?>",
            data: data,
            context: this,
            success: function(resp){
                var row = dimensionPriceForm(resp);
                $(this).parent().parent().replaceWith(row);
            }
        });
        
    });


    $(document).on('click', '#add_new_price', function(e){
        e.preventDefault();
        
        var row = dimensionPriceForm();
        
        $('td.dataTables_empty').parent().remove();
        $('#prices_and_dimensions tbody').append(row);
        
    });
    
    
    function dimensionPriceForm(data){
        if(!data)
            data = {
                id: 0,
                dimension_id: 0,
                price: '',
                availability: '',
                new: false,
                most_frequently_purchased: false,
                promoted: false,
                discount_id: 0,
                promotion: false,
                promotion_price: ''
            };
        
        var dimension = $('<td/>');
        var price = $('<td/>');
        var availability = $('<td/>');
        var lastnew = $('<td/>');
        var mostfrequentlypurchased = $('<td/>');
        var promoted = $('<td/>');
        var discount = $('<td/>');
        var promotion = $('<td/>');
        var options = $('<td/>');
//        
        $('<?php echo $this->form->getMostFrequentlyPurchasedElement(); ?>').appendTo(mostfrequentlypurchased).attr('checked', data.most_frequently_purchased);
        
        $('<?php echo $this->form->getNewElement(); ?>').appendTo(lastnew).attr('checked', data.new);
        
        $('<?php //echo $this->form->getDimensionElement($this->dimensions); ?>').appendTo(dimension).attr('value', data.dimension_id);
        
        $('<?php echo $this->form->getPriceElement(); ?>').appendTo(price).attr('value', data.price);
        
        $('<?php echo $this->form->getAvailabilityElement(); ?>').appendTo(availability).attr('value', data.availability);
        
        $('<?php echo $this->form->getPromotedElement(); ?>').appendTo(promoted).attr('checked', data.promoted);
        
        $('<?php echo $this->form->getPromotionElement().$this->form->getPromotionPriceElement(); ?>').appendTo(promotion).parent().find('#newpromotion').attr('checked', data.promotion).parent().find('#newpromotionprice').attr('value', data.promotion_price).attr('readonly', (data.promotion?false:true));
        
        $('<?php echo $this->form->getDiscountsElement($this->discounts); ?>').appendTo(discount).attr('value', data.discount_id);
        
        $('<a href="'+(data.id?'<?php echo $this->adminUrl('edit-dimension-price', 'product'); ?>':'<?php //echo $this->adminUrl('add-dimension-price', 'product'); ?>')+'" class="add_price btn btn-success btn-mini" value="'+data.id+'"><?php //echo $this->translate('Save') ?></a>').appendTo(options);
        
        var row = $('<tr/>').append(dimension)
                            .append(price)
                            .append(availability)
                            .append(lastnew)
                            .append(mostfrequentlypurchased)
                            .append(promoted)
                            .append(promotion)
                            .append(discount)
                            .append(options);
                    
        return row;
    }
    
    
    $(document).on('click', '#promotion', function(){
        var value = $(this).attr('checked');
        if(value){
            $('#promotion_price').attr('readonly', false);
        }else{
            $('#promotion_price').attr('readonly', true);
        }
    });
</script>
<div class="row-fluid">

    <div class="grid_12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit product') ?> <?php echo $this->product->Translation[$this->language]->name ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post">
                   
                    <?php echo $this->form->id ?>
                    <?php echo $this->form->code ?>
                    <?php // echo $this->form->producer_id->setAttribs(array('class' => 'nostyle')) ?>
                     <br/>
                    <?php if ($this->form->category_id->hasErrors()): ?>
                          <div class="box" style="border: 1px solid red; width: 97%;">     
                        <?php else: ?>
                          <div class="box" style="border: 1px solid black; width: 97%;"> 
                        <?php endif; ?>
                            <div class="title">
                            <h4>
                                <span class="icon16 iconic-icon-list-nested"></span>
                                <span><?php echo $this->translate('Categories') ?></span>
                            </h4>

                            </div>
                            <div id="category_tree_selection">
                                <?php echo $this->partial('category-tree-selection.phtml', 'product', array('tree' => $this->categoryTree, 'parent' => $this->parent, 'selectedIds' => $this->form->category_id->getValue(), 'adminLanguage' => $this->adminLanguage)) ?>
                            </div>    
                          </div>
                              
                              
  
                    <span style="display: none;">
                        <?php echo $this->form->category_id; ?>
                    </span>
                    <?php echo $this->form->collection_id; ?>
                    <?php echo $this->form->price; ?>
                    <?php // echo $this->form->discount_id->setAttribs(array('class' => 'nostyle')) ?>
                    <?php echo $this->form->availability ?>
                    <?php echo $this->form->new; ?>
                    <?php echo $this->form->promoted; ?>
                    <?php echo $this->form->most_frequently_purchased; ?>
                              
                    <?php echo $this->form->promotion; ?>
                    <?php echo $this->form->promotion_price; ?>
                   
                    <div class="page-header">
                         <h4><?php echo $this->translate('Main photo') ?></h4>
                    </div>  
                    <div id="itemCon">
                        <ul id="main_photo_con" class="galleryView center">
                            <li class="pull-left">
                                <?php if($this->product->get('PhotoRoot')->getOffset()): ?>
                                <a id="main_photo" href="/media/photos/<?php echo $this->product->get('PhotoRoot')->getOffset() ?>/<?php echo $this->product->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->product->get('PhotoRoot')->getTitle() ?>">
                                    <img src="/media/photos/<?php echo $this->product->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->product->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->product->get('PhotoRoot')->getOffset() ?>/<?php echo $this->product->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->product->get('PhotoRoot')->getTitle() ?>">
                                </a>
                                <?php else: ?>
                                <a id="main_photo" href="/images/gallery/preload.png" title="<?php echo $this->translate('No photo') ?>">
                                    <img src="/images/gallery/preload.png" data-original="/images/gallery/preload.png" alt="<?php echo $this->translate('No photo') ?>">
                                </a>
                                <?php endif; ?>
                                <div class="actionBtn">
                                    <a href="<?php echo $this->adminUrl('edit-product-main-photo', 'product', array('product-id' => $this->product->getId(), 'id' => $this->product->get('PhotoRoot')->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
                                    <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                                    <a href="#" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
                                </div>
                            </li>
                        </ul>
                    </div> 
                    
                    <div class="clearfix"></div>
                    <div class="page-header">
                         <h4><?php echo $this->translate('Gallery View') ?></h4>
                    </div>                  
                      <div id="itemContainer">           
                        <button href="#" id="add-photo" style="width: 120px;"><?php echo $this->translate('Add photo') ?></button>
                        <ul id="main_photo_container" class="galleryView center">                           
                                <?php echo $this->partial('admin/product-main-photo.phtml', 'product', array('photos' => $this->productPhotos, 'product' => $this->product)) ?>
                        </ul>
                      </div>
                          
                 
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-product', 'product') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>             
                </form>
            
            </div>
            
        </div>
    </div>   
    
</div>
</div>
<div id="explorer" class="dialog"><div id="elfinder"></div></div>
<div id="explorer2" class="dialog"><div id="elfinder2"></div></div>