<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#dimensions_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-dimension-data', 'product') ?>",
        "aaSorting": [[ 0, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#dimensions_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-rulers"></span>
                    <span><?php echo $this->translate('Dimensions') ?></span>
               </h4> 
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="dimensions_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Dimension') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
    
    <?php echo $this->action('add-dimension', 'admin', 'product'); ?>
    
</div>