<?php if ($this->censorCount > 1): ?>
    <!-- Previous censor link -->
    <?php if (isset($this->previous)): ?>
        <a class="prev" href="<?php echo $this->adminUrl('list-censor', 'censor', array('censor' => $this->previous)); ?>"><span>&laquo;</span></a>
    <?php else: ?>
        <a class="prev"><span>&laquo;</span></a>
    <?php endif; ?>

    <!-- Numbered censor links -->
    <?php foreach ($this->censorsInRange as $censor): ?>
    <?php if ($censor != $this->current): ?>
        <a href="<?php echo $this->adminUrl('list-censor', 'censor', array('censor' => $censor)) ?>"><?php echo $censor; ?></a>
    <?php else: ?>
        <a class="active" href="#"><?php echo $censor; ?></a>
    <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next censor link -->
    <?php if (isset($this->next)): ?>
        <a class="next" href="<?php echo $this->adminUrl('list-censor', 'censor', array('censor' => $this->next)); ?>"><span>&raquo;</span></a>
    <?php else: ?>
        <a class="next"><span>&raquo;</span></a>
    <?php endif; ?>
<?php endif; ?>