<?php foreach($this->photos as $photo): ?>
<li class="pull-left">
    <?php if($photo->getOffset()): ?>
    <div>
        <a id="main_photo" href="/media/photos/<?php echo $photo->getOffset() ?>/<?php echo $photo->getFilename() ?>" rel="prettyPhoto" title="<?php echo $photo->getTitle() ?>">
            <img src="/media/photos/<?php echo $photo->getOffset() ?>/126x126/<?php echo $photo->getFilename() ?>" data-original="/media/photos/<?php echo $photo->getOffset() ?>/<?php echo $photo->getFilename() ?>" alt="<?php echo $photo->getTitle() ?>" />
        </a>
        <div class="actionBtn">
            <a class="move" href="<?php echo $this->adminUrl('move-gallery-photo', 'gallery', array('id' => $photo->id, 'move' => 'up', 'gallery' => $this->gallery->id)) ?>"><span class="icon16 minia-icon-arrow-left white"></span></a>
            <a href="<?php echo $this->adminUrl('edit-gallery-photo', 'gallery', array('gallery-id' => $this->gallery->getId(), 'id' => $photo->getId())) ?>" class="edit"><span class="icon16 icomoon-icon-pencil-2 white"></span></a>
            <a href="#" rel="<?php echo $photo->id; ?>" class="delete"><span class="icon16 icomoon-icon-cancel-4 white"></span></a>
            <a class="move" href="<?php echo $this->adminUrl('move-gallery-photo', 'gallery', array('id' => $photo->id, 'move' => 'down', 'gallery' => $this->gallery->id)) ?>"><span class="icon16 minia-icon-arrow-right white"></span></a>

        </div>
    </div>
    <?php endif; ?>
    
</li>
<?php endforeach; ?>