<script type="text/javascript">
$(document).ready(function() {
    
    var oTable = $("#item_table").dataTable( {
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bPaginate": false,
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": false,
        "bLengthChange": false,

        "sAjaxSource": "<?php echo $this->adminUrl('list-order-item-data', 'order', array('id' => $this->order->getId())) ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' },
        ]
    });
    
    $("#item_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    var oTable2 = $("#payment_table").dataTable( {
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bPaginate": false,
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": false,
        "bInfo": false,
        "bLengthChange": false,

        "sAjaxSource": "<?php echo $this->adminUrl('payment-order-data', 'order', array('id' => $this->order->getId())) ?>",
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
        ]
    });
    
    $("#payment_table").bind("update", function(e) {
        oTable2.fnReloadAjax();
    });
    
    var oTable3 = $("#delivery_table").dataTable( {
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bPaginate": false,
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": false,
        "bLengthChange": false,
         "bInfo": false,
        "sAjaxSource": "<?php echo $this->adminUrl('delivery-order-data', 'order', array('id' => $this->order->getId())) ?>",
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
        ]
    });
    
    $("#delivery_table").bind("update", function(e) {
        oTable3.fnReloadAjax();
    });
    
});
</script>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-user-3"></span>
                    <span><?php echo $this->translate('Customer data') ?></span>
                    <div class="box-form right">
                        <?php echo $this->translate('Invoice') ?>
                        <a href="<?php echo $this->adminUrl('pdf-invoice', 'order', array('id' => $this->order['id'], 'pdf' => 1)) ?>" class="tip" title="<?php echo $this->translate('PDF') ?>"><span class="icon24 icomoon-icon-file-pdf"></span></a> 
                    </div>   
                </h4>
            </div>
            <div class="content" style="min-height: 162px;">
                <div style="float:left; padding-left: 20px; width: 250px;">
                <?php echo $this->order['Delivery']['DeliveryAddress']['name'].'<br/>'; ?>   
                <?php echo $this->order['Delivery']['DeliveryAddress']['address'].'<br/>'; ?>    
                <?php echo $this->order['Delivery']['DeliveryAddress']['postal_code'].' '.$this->order['Delivery']['DeliveryAddress']['city'].'<br/>'; ?>  
                <?php echo $this->order['Delivery']['DeliveryAddress']['province'].'<br/>'; ?> 
                <?php // echo $this->order['Delivery']['DeliveryAddress']['phone']; ?>  
                </div>
                <div style="float:left;">
                    Dane do wysyłki:<br/>
                    <?php if ($this->order['Delivery']['DeliveryAddress']['status'] == 1):
                        echo $this->order['Delivery']['DeliveryAddress']['name'].'<br/>'; 
                        echo $this->order['Delivery']['DeliveryAddress']['address'].'<br/>'; 
                        echo $this->order['Delivery']['DeliveryAddress']['postal_code'].' '.$this->order['Delivery']['DeliveryAddress']['city'].'<br/>'; 
                        echo $this->order['Delivery']['DeliveryAddress']['province'].'<br/>';  
                    else:
                        echo 'takie same';
                    endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit order status') ?></span>
                </h4>
            </div>
            <div class="content">
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->order_status_id->setAttribs(array('class' => 'nostyle')) ?>
                    <?php echo $this->form->id ?>

                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-order', 'order'); ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>       
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Order items') ?></span>
                </h4> 
            </div>
            <div class="content clearfix">
                <table id="item_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Product name') ?></th>
                        <th><?php echo $this->translate('Price') ?> [zł]</th>
                        <th><?php echo $this->translate('Count') ?></th>
                        <th><?php echo $this->translate('Discount') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>  
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-coin"></span>
                    <span><?php echo $this->translate('Payment') ?></span>
                </h4>   
            </div>
            <div class="content clearfix">
                <table id="payment_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Payment method') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>  
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 minia-icon-envelope"></span>
                    <span><?php echo $this->translate('Delivery') ?></span>
               </h4>
            </div>
            <div class="content clearfix">
                <table id="delivery_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Delivery method') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
