<?php

/**
 * Partner_Model_Doctrine_PartnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Partner_Model_Doctrine_PartnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Partner_Model_Doctrine_PartnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partner_Model_Doctrine_Partner');
    }
}