<?php

/**
 * Partner_Model_Doctrine_Partner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Partner
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Partner_Model_Doctrine_Partner extends Partner_Model_Doctrine_BasePartner
{
    public static $partnerPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        'x220' => 'Main photo',
        '600x' => 'Big photo'
    );
    
    public static function getPartnerPhotoDimensions() {
        return self::$partnerPhotoDimensions;
    }
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function getMetatagId() {
        return $this->_get('metatag_id');    
    }
    
    public function isStatus() {
        return $this->_get('status');
    }
    
    public function setStatus($status = true) {
        $this->_set('status', $status);
    }
    
    public function setUp() {
        parent::setUp();
        $this->hasOne('User_Model_Doctrine_User as LastEditor', array(
            'local' => 'last_editor_id',
            'foreign' => 'id'
        ));
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        $this->hasMany('Media_Model_Doctrine_Photo as Photos', array(
            'local' => 'photo_root_id',
            'foreign' => 'root_id'
        ));
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
    }
}