<?php

/**
 * Partner_Model_Doctrine_PartnerTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Partner
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Partner_Model_Doctrine_PartnerTranslation extends Partner_Model_Doctrine_BasePartnerTranslation
{

}