<?php

/**
 * Partner_Model_Doctrine_PartnerTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Partner_Model_Doctrine_PartnerTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Partner_Model_Doctrine_PartnerTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partner_Model_Doctrine_PartnerTranslation');
    }
}