<?php

/**
 * Offer_Model_Doctrine_BaseParameterTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $description
 * @property string $unit
 * @property boolean $range
 * @property Doctrine_Collection $OfferTemplateParameterTemplate
 * @property Doctrine_Collection $NoticeTemplateParameterTemplate
 * @property Doctrine_Collection $Parameters
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Offer_Model_Doctrine_BaseParameterTemplate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('offer_parameter_template');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('unit', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('range', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Offer_Model_Doctrine_OfferTemplateParameterTemplate as OfferTemplateParameterTemplate', array(
             'local' => 'id',
             'foreign' => 'parameter_template_id'));

        $this->hasMany('Offer_Model_Doctrine_NoticeTemplateParameterTemplate as NoticeTemplateParameterTemplate', array(
             'local' => 'id',
             'foreign' => 'parameter_template_id'));

        $this->hasMany('Offer_Model_Doctrine_OfferParameter as Parameters', array(
             'local' => 'id',
             'foreign' => 'parameter_template_id'));
    }
}