<?php

/**
 * Offer_Model_Doctrine_BaseOfferParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parameter_template_id
 * @property string $value
 * @property string $value_to
 * @property boolean $required
 * @property Offer_Model_Doctrine_Offer $Offer
 * @property Offer_Model_Doctrine_ParameterTemplate $ParameterTemplate
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Offer_Model_Doctrine_BaseOfferParameter extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('offer_offer_parameter');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('parameter_template_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('value_to', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('required', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Offer_Model_Doctrine_Offer as Offer', array(
             'local' => 'id',
             'foreign' => 'parameter_root_id'));

        $this->hasOne('Offer_Model_Doctrine_ParameterTemplate as ParameterTemplate', array(
             'local' => 'parameter_template_id',
             'foreign' => 'id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $this->actAs($nestedset0);
    }
}