<?php

/**
 * Offer_Model_Doctrine_BaseCategoryPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $period
 * @property integer $price
 * @property Offer_Model_Doctrine_Category $Category
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Offer_Model_Doctrine_BaseCategoryPrice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('offer_category_price');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('period', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('price', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('category_period', array(
             'fields' => 
             array(
              0 => 'category_id',
              1 => 'period',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Offer_Model_Doctrine_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}