<?php

/**
 * Offer_Model_Doctrine_BaseDeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $offer_id
 * @property integer $notice_id
 * @property integer $status
 * @property boolean $contact_revealed
 * @property integer $client_mark
 * @property Offer_Model_Doctrine_Offer $Offer
 * @property Offer_Model_Doctrine_Notice $Notice
 * @property Doctrine_Collection $Messages
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Offer_Model_Doctrine_BaseDeal extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('offer_deal');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('offer_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('notice_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('status', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('contact_revealed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('client_mark', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Offer_Model_Doctrine_Offer as Offer', array(
             'local' => 'offer_id',
             'foreign' => 'id'));

        $this->hasOne('Offer_Model_Doctrine_Notice as Notice', array(
             'local' => 'notice_id',
             'foreign' => 'id'));

        $this->hasMany('Offer_Model_Doctrine_DealMessage as Messages', array(
             'local' => 'id',
             'foreign' => 'deal_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}