<?php

/**
 * Offer_Model_Doctrine_BaseOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property integer $offer_template_id
 * @property integer $category_id
 * @property integer $user_id
 * @property boolean $extended
 * @property string $title
 * @property clob $content
 * @property integer $parameter_root_id
 * @property integer $province_id
 * @property integer $city_id
 * @property Offer_Model_Doctrine_OfferTemplate $OfferTemplate
 * @property Offer_Model_Doctrine_Category $Category
 * @property Doctrine_Collection $Parameters
 * @property Offer_Model_Doctrine_OfferParameter $ParameterRoot
 * @property Doctrine_Collection $Deals
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Offer_Model_Doctrine_BaseOffer extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('offer_offer');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('code', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('offer_template_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('extended', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('parameter_root_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('province_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('city_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Offer_Model_Doctrine_OfferTemplate as OfferTemplate', array(
             'local' => 'offer_template_id',
             'foreign' => 'id'));

        $this->hasOne('Offer_Model_Doctrine_Category as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('Offer_Model_Doctrine_OfferParameter as Parameters', array(
             'local' => 'parameter_root_id',
             'foreign' => 'root_id'));

        $this->hasOne('Offer_Model_Doctrine_OfferParameter as ParameterRoot', array(
             'local' => 'parameter_root_id',
             'foreign' => 'id'));

        $this->hasMany('Offer_Model_Doctrine_Deal as Deals', array(
             'local' => 'id',
             'foreign' => 'offer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}