<?php

/**
 * Offer_Model_Doctrine_CategoryPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_CategoryPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_CategoryPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_CategoryPrice');
    }
    
    public function getCategoryPriceQuery() {
        $q = $this->createQuery('p')
                ->addSelect('p.*')
                ->addSelect('c.*')
                ->leftJoin('p.Category c')
                ;
        return $q;
    }
    
    public function findOneByCategoryIdAndPeriod($categoryId, $period) {
        $q = $this->getCategoryPriceQuery();
        $q->andWhere('p.category_id = ?', $categoryId);
        $q->andWhere('p.period = ?', $period);
        return $q->fetchOne();
    }
}