<?php

/**
 * Offer_Model_Doctrine_DealMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_DealMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_DealMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_DealMessage');
    }
    
    public function getDealMessageQuery() {
        $q = $this->createQuery('dm')
                ->select('dm.*')
                ;
        return $q;
    }
}