<?php

/**
 * Offer_Model_Doctrine_DealMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Offer_Model_Doctrine_DealMessage extends Offer_Model_Doctrine_BaseDealMessage
{
    const RECIPIENT_AGENT = 'agent';
    const RECIPIENT_CLIENT = 'client';
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setDealId($dealId) {
        $this->_set('deal_id', $dealId);
    }
    
    public function getDealId() {
        return $this->_get('deal_id');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
    public function setContent($content) {
        $this->_set('content', $content);
    }
    
    public function getContent() {
        return $this->_get('content');
    }
    
    public function setRecipient($recipient) {
        $this->_set('recipient', $recipient);
    }
    
    public function getRecipient() {
        return $this->_get('recipient');
    }
    
    public function setStatus($status) {
        $this->_set('status', $status);
    }
    
    public function getStatus() {
        return $this->_get('status');
    }
    
    public function setContainsCard($containsCard) {
        $this->_set('contains_card', $containsCard);
    }
    
    public function containsCard() {
        return $this->_get('contains_card');
    }
}