<?php

/**
 * Offer_Model_Doctrine_DealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_DealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_DealTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_Deal');
    }
    
    public function getQueryWithMessages() {
        $q = $this->createQuery('d')
                ->addSelect('d.*')
                ->addSelect('dm.*')
                ->leftJoin('d.Messages dm')
                ->addOrderBy('dm.created_at DESC')
                ;
        return $q;
    }
    
    public function getJoinQueryWithOfferAndNoticeAndUserAndProfile(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->getQueryWithMessages();
        }
        $q->addSelect('o.*')
            ->addSelect('ou.*')
            ->addSelect('oup.*')
            ->addSelect('ouppr.*')
            ->addSelect('n.*')
            ->addSelect('nu.*')
            ->addSelect('nup.*')
            ->addSelect('nuppr.*')
            ->leftJoin('d.Offer o')
            ->leftJoin('o.User ou')
            ->leftJoin('ou.Profile oup')
            ->leftJoin('oup.PhotoRoot ouppr')
            ->leftJoin('d.Notice n')
            ->leftJoin('n.User nu')
            ->leftJoin('nu.Profile nup')
            ->leftJoin('nup.PhotoRoot nuppr')
            ;
        return $q;
    }
    
    public function getQueryWithOfferAndNoticeByOfferIdAndNoticeId($offerId, $noticeId) {
        $q = $this->createQuery('d')
                ->addSelect('d.*')
                ->addSelect('o.*')
                ->addSelect('n.*')
                ->leftJoin('d.Offer o')
                ->leftJoin('d.Notice n')
                ->andWhere('d.offer_id = ?', $offerId)
                ->andWhere('d.notice_id = ?', $noticeId)
                ;
        return $q;
    }
    
    public function getQueryWithMessagesByOfferIdAndDealId($offerId, $dealId) {
        $q = $this->getQueryWithMessages()
                ->andWhere('d.offer_id = ?', $offerId)
                ->andWhere('d.id = ?', $dealId)
                ->orderBy('dm.created_at DESC')
                ;
        return $q;
    }
    
    public function getQueryWithMessagesByNoticeIdAndDealId($noticeId, $dealId) {
        $q = $this->getQueryWithMessages()
                ->leftJoin('d.Messages dm')
                ->andWhere('d.notice_id = ?', $noticeId)
                ->andWhere('d.id = ?', $dealId)
                ->orderBy('dm.created_at DESC')
                ;
        return $q;
    }
}