<?php

/**
 * Offer_Model_Doctrine_NoticeTemplateParameterTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_NoticeTemplateParameterTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_NoticeTemplateParameterTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_NoticeTemplateParameterTemplate');
    }
}