<?php

/**
 * Offer_Model_Doctrine_Notice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Offer_Model_Doctrine_Notice extends Offer_Model_Doctrine_BaseNotice
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setCategoryId($categoryId) {
        $this->_set('category_id', $categoryId);
    }
    
    public function getCategoryId() {
        return $this->_get('category_id');
    }
    
    public function setParameterRootId($parameterRootId) {
        $this->_set('parameter_root_id', $parameterRootId);
    }
    
    public function getParameterRootId() {
        return $this->_get('parameter_root_id');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
    public function setContent($content) {
        $this->_set('content', $content);
    }
    
    public function getContent() {
        return $this->_get('content');
    }
    
    public function setPublish($publish = true) {
        $this->_set('publish', $publish);
    }
    
    public function isPublish() {
        return $this->_get('publish');
    }
    
    public function setPublishDate($publishDate) {
        $this->_set('publish_date', $publishDate);
    }
    
    public function getPublishDate() {
        return $this->_get('publish_date');
    }
    
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign_id' => 'id'
        ));
        parent::setUp();
    }
}