<?php

/**
 * Offer_Model_Doctrine_NoticeTemplateParameterTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Offer_Model_Doctrine_NoticeTemplateParameterTemplate extends Offer_Model_Doctrine_BaseNoticeTemplateParameterTemplate
{

}