<?php

/**
 * Offer_Model_Doctrine_OfferTemplateParameterTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_OfferTemplateParameterTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_OfferTemplateParameterTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_OfferTemplateParameterTemplate');
    }
}