<?php

/**
 * Offer_Model_Doctrine_Offer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Offer_Model_Doctrine_Offer extends Offer_Model_Doctrine_BaseOffer
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setCode($code) {
        $this->_set('code', $code);
    }
    
    public function getCode() {
        return $this->_get('code');
    }
    
    public function setParameterRootId($parameterRootId) {
        $this->_set('parameter_root_id', $parameterRootId);
    }
    
    public function getParameterRootId() {
        return $this->_get('parameter_root_id');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
    public function setContent($content) {
        $this->_set('content', $content);
    }
    
    public function getContent() {
        return $this->_get('content');
    }
    
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign_id' => 'id'
        ));
        parent::setUp();
    }
}