<?php

/**
 * Offer_Model_Doctrine_OfferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_OfferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_OfferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_Offer');
    }
    
    public function getOfferQueryWithCategoryAndOfferTemplateAndParameters() {
        $q = $this->createQuery('o')
                ->addSelect('c.*')
                ->addSelect('o.*')
                ->addSelect('ot.*')
                ->addSelect('p.*')
                ->leftJoin('o.Category c')
                ->leftJoin('o.OfferTemplate ot')
                ->leftJoin('o.Parameters p')
                ->andWhere('p.level > ?', 0)
                ->addOrderBy('p.lft ASC')
                ;
        return $q;
    }
    
    public function getOfferQueryWithCategoryAndOfferTemplateAndParametersById($id) {
        $q = $this->getOfferQueryWithCategoryAndOfferTemplateAndParameters();
        $q->andWhere('o.id = ?', $id);
//        $q = $this->createQuery('o')
//                ->addSelect('c.*')
//                ->addSelect('o.*')
//                ->addSelect('ot.*')
//                ->addSelect('p.*')
//                ->leftJoin('o.Category c')
//                ->leftJoin('o.OfferTemplate ot')
//                ->leftJoin('o.Parameters p')
//                ->andWhere('p.level > ?', 0)
//                ->andWhere('o.id = ?', $id)
//                ->addOrderBy('p.lft ASC')
//                ;
        return $q;
    }
    
    public function getOfferQueryWithParametersByUserId($userId) {
        $q = $this->createQuery('o')
                ->select('o.*')
                ->addSelect('p.*')
                ->addSelect('d.*, COUNT(DISTINCT d.id) as deal_count')
                ->addSelect('dm.*, COUNT(DISTINCT dm.id) as deal_message_count')
                ->leftJoin('o.Parameters p')
                ->leftJoin('o.Deals d')
                ->leftJoin('d.Messages dm')
                ->andWhere('p.level > ?', 0)
                ->andWhere('o.user_id = ?', $userId)
                ->addOrderBy('p.lft ASC')
                ;
        return $q;
    }
    
    public function getOfferQueryWithDealsAndDealMessages(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->getOfferQueryWithCategoryAndOfferTemplateAndParameters();
        }
        $q->addSelect('d.*, COUNT(d.id) as deal_count');
        $q->addSelect('dm.*, COUNT(dm.id) as deal_message_count');
        $q->addSelect('u.*');
        $q->leftJoin('o.Deals d');
        $q->leftJoin('d.Messages dm');
        $q->leftJoin('o.User u');
        return $q;
    }
}