<?php

/**
 * Offer_Model_Doctrine_Parameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Offer
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Offer_Model_Doctrine_Parameter extends Offer_Model_Doctrine_BaseParameter
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setValue($value) {
        $this->_set('value', $value);
    }
    
    public function getValue() {
        return $this->_get('value');
    }
    
    public function setValueTo($valueTo) {
        $this->_set('value_to', $valueTo);
    }
    
    public function getValueTo() {
        return $this->_get('value_to');
    }
}