<?php

/**
 * Offer_Model_Doctrine_ParameterTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Offer_Model_Doctrine_ParameterTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Offer_Model_Doctrine_ParameterTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Offer_Model_Doctrine_ParameterTemplate');
    }
    
    public function getSortedParameterTemplates() {
        $q = $this->createQuery('t')
                ->select('t.*')
                ->addOrderBy('t.name ASC')
                ;
        return $q->execute();
    }
    
    public function findAllByNames($names, $hydrationMode = Doctrine_Core::HYDRATE_RECORD) {
        $q = $this->createQuery('t')
                ->select('t.*')
                ->where('t.name IN ?', array($names))
                ;
        return $q->execute(array(), $hydrationMode);
    }
}