<?php

/**
 * Article_Model_Doctrine_Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Article
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article_Model_Doctrine_Article extends Article_Model_Doctrine_BaseArticle
{
    public static $articlePhotoDimensions = array(
        '48x48' => 'Sidebar thumbnail',
        '126x126' => 'Admin thumbnail',                  // admin
        '255x122' => 'Excerpt thumbnail',
        '650x262' => 'Main photo'
    );
    
    public static function getArticlePhotoDimensions() {
        return self::$articlePhotoDimensions;
    }
    
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setTitle($title) {
        $this->_set('title', $title);
    }
    
    public function getTitle() {
        return $this->_get('title');
    }
    
    public function setStatus($status) {
        $this->_set('status', $status);
    }
    
    public function getStatus() {
        return $this->_get('status');
    }
    
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign' => 'id'
        ));
        $this->hasOne('Offer_Model_Doctrine_Category as Category', array(
            'local' => 'category_id',
            'foreign' => 'id'
        ));
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatag', array(
            'local' => 'metatag_id',
            'foreign' => 'id'
        ));
        $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}