<?php

/**
 * Article_Model_Doctrine_ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Article_Model_Doctrine_ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Article_Model_Doctrine_ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article_Model_Doctrine_Article');
    }
    
    public function getArticleQuery() {
        $q = $this->createQuery('a');
        $q->addSelect('a.*');
        $q->addSelect('c.*');
        $q->addSelect('u.*');
        $q->addSelect('pr.*');
        $q->leftJoin('a.Category c');
        $q->leftJoin('a.User u');
        $q->leftJoin('a.PhotoRoot pr');
        return $q;
    }
}