<?php

/**
 * Article_Model_Doctrine_ArticleTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Article
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article_Model_Doctrine_ArticleTranslation extends Article_Model_Doctrine_BaseArticleTranslation
{

}