<?php

/**
 * Article_Model_Doctrine_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Article
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article_Model_Doctrine_Category extends Article_Model_Doctrine_BaseCategory
{
    public function setId($id) {
        $this->_set('id', $id);
    }
    
    public function getId() {
        return $this->_get('id');
    }
    
    public function setName($name) {
        $this->_set('name', $name);
    }
    
    public function getName() {
        return $this->_get('name');
    }
    
    public function setAlias($alias) {
        $this->_set('alias', $alias);
    }
    
    public function getAlias() {
        return $this->_get('alias');
    }
    
    public function setSlug($slug) {
        $this->_set('slug', $slug);
    }
    
    public function getSlug() {
        return $this->_get('slug');
    }
}