<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#article_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-message-data', 'newsletter') ?>",
        "aaSorting": [[ 1, "desc" ]],
        "aoColumns": [
            null,
            null,
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#article_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    $("#subscribers").select2();
    $("#groups").select2();
});
</script>

<div class="row-fluid">

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit message') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="#" method="POST" enctype="multipart/form-data">
                                        
                    <?php echo $this->form->title ?>
                    <?php echo $this->form->content ?>
                    <?php echo $this->form->type ?>
                    <?php echo $this->form->subscribers ?>
                    <?php echo $this->form->groups ?>
                    
                    <?php echo $this->form->id ?>
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-category', 'news') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                </form>
            
            </div>
            
        </div>
        
    </div>

    <div class="span6">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-mail-4"></span>
                    <span><?php echo $this->translate('Messages') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">

                <table id="article_table" cellpadding="0" cellspacing="0" border="0" class="responsive display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Title') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            
            </div>

        </div><!-- End .box -->

    </div>


</div>