<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('article_article', 'status', 'integer', '2', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('article_article', 'status');
    }
}