<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('product_dimension');
        $this->dropTable('product_dimension_price');
        $this->dropTable('product_product_comment');
        $this->dropTable('product_attachment_translation');
        $this->dropTable('product_category_translation');
        $this->dropTable('product_discount_translation');
        $this->dropTable('product_producer_translation');
        $this->dropTable('product_product_translation');
        $this->createTable('product_collection', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'discount_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'status' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'metatag_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'views' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '4',
             ),
             'clicks' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '4',
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_collection_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_product_collection', array(
             'product_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'collection_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'product_id',
              1 => 'collection_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('product_attachment', 'title', 'string', '255', array(
             ));
        $this->addColumn('product_attachment', 'slug', 'string', '255', array(
             ));
        $this->addColumn('product_attachment', 'description', 'clob', '', array(
             ));
        $this->addColumn('product_category', 'name', 'string', '255', array(
             ));
        $this->addColumn('product_category', 'description', 'clob', '', array(
             ));
        $this->addColumn('product_category', 'slug', 'string', '255', array(
             ));
        $this->addColumn('product_discount', 'name', 'string', '255', array(
             ));
        $this->addColumn('product_producer', 'name', 'string', '255', array(
             ));
        $this->addColumn('product_producer', 'description', 'clob', '', array(
             ));
        $this->addColumn('product_producer', 'slug', 'string', '255', array(
             ));
        $this->addColumn('product_product', 'name', 'string', '255', array(
             ));
        $this->addColumn('product_product', 'slug', 'string', '255', array(
             ));
        $this->addColumn('product_product', 'description', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->createTable('product_dimension', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'width' => 
             array(
              'type' => 'integer',
              'length' => '3',
             ),
             'height' => 
             array(
              'type' => 'integer',
              'length' => '3',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_dimension_price', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'dimension_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'availability' => 
             array(
              'type' => 'integer',
              'default' => '1',
              'length' => '1',
             ),
             'discount_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'new' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'promoted' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'promotion' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'promotion_price' => 
             array(
              'type' => 'decimal',
              'default' => '0',
              'length' => '18',
             ),
             'most_frequently_purchased' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '8',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_product_comment', array(
             'product_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'comment_id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'product_id',
              1 => 'comment_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_category_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_discount_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_producer_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('product_product_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('product_collection');
        $this->dropTable('product_collection_translation');
        $this->dropTable('product_product_collection');
        $this->removeColumn('product_attachment', 'title');
        $this->removeColumn('product_attachment', 'slug');
        $this->removeColumn('product_attachment', 'description');
        $this->removeColumn('product_category', 'name');
        $this->removeColumn('product_category', 'description');
        $this->removeColumn('product_category', 'slug');
        $this->removeColumn('product_discount', 'name');
        $this->removeColumn('product_producer', 'name');
        $this->removeColumn('product_producer', 'description');
        $this->removeColumn('product_producer', 'slug');
        $this->removeColumn('product_product', 'name');
        $this->removeColumn('product_product', 'slug');
        $this->removeColumn('product_product', 'description');
    }
}