<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('product_category', 'product_category_photo_root_id_media_photo_id');
        $this->dropForeignKey('product_category', 'product_category_metatag_id_default_metatag_id');
        $this->dropForeignKey('product_comment', 'product_comment_user_id_user_user_id');
        $this->dropForeignKey('product_preview', 'product_preview_photo_root_id_media_photo_id');
        $this->dropForeignKey('product_preview', 'product_preview_metatag_id_default_metatag_id');
        $this->dropForeignKey('product_producer', 'product_producer_photo_root_id_media_photo_id');
        $this->dropForeignKey('product_producer', 'product_producer_metatag_id_default_metatag_id');
        $this->dropForeignKey('product_product', 'product_product_photo_root_id_media_photo_id');
        $this->dropForeignKey('product_product', 'product_product_metatag_id_default_metatag_id');
        $this->createForeignKey('product_collection_translation', 'product_collection_translation_id_product_collection_id', array(
             'name' => 'product_collection_translation_id_product_collection_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'product_collection',
             ));
        $this->createForeignKey('product_collection_translation', 'product_collection_translation_id_product_collection_id_1', array(
             'name' => 'product_collection_translation_id_product_collection_id_1',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'product_collection',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('product_product_collection', 'product_product_collection_collection_id_product_collection_id', array(
             'name' => 'product_product_collection_collection_id_product_collection_id',
             'local' => 'collection_id',
             'foreign' => 'id',
             'foreignTable' => 'product_collection',
             ));
        $this->createForeignKey('product_product_collection', 'product_product_collection_product_id_product_product_id', array(
             'name' => 'product_product_collection_product_id_product_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product_product',
             ));
        $this->addIndex('product_collection_translation', 'product_collection_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('product_product_collection', 'product_product_collection_collection_id', array(
             'fields' => 
             array(
              0 => 'collection_id',
             ),
             ));
        $this->addIndex('product_product_collection', 'product_product_collection_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('product_category', 'product_category_photo_root_id_media_photo_id', array(
             'name' => 'product_category_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('product_category', 'product_category_metatag_id_default_metatag_id', array(
             'name' => 'product_category_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('product_comment', 'product_comment_user_id_user_user_id', array(
             'name' => 'product_comment_user_id_user_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('product_preview', 'product_preview_photo_root_id_media_photo_id', array(
             'name' => 'product_preview_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('product_preview', 'product_preview_metatag_id_default_metatag_id', array(
             'name' => 'product_preview_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('product_producer', 'product_producer_photo_root_id_media_photo_id', array(
             'name' => 'product_producer_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('product_producer', 'product_producer_metatag_id_default_metatag_id', array(
             'name' => 'product_producer_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->createForeignKey('product_product', 'product_product_photo_root_id_media_photo_id', array(
             'name' => 'product_product_photo_root_id_media_photo_id',
             'local' => 'photo_root_id',
             'foreign' => 'id',
             'foreignTable' => 'media_photo',
             ));
        $this->createForeignKey('product_product', 'product_product_metatag_id_default_metatag_id', array(
             'name' => 'product_product_metatag_id_default_metatag_id',
             'local' => 'metatag_id',
             'foreign' => 'id',
             'foreignTable' => 'default_metatag',
             ));
        $this->dropForeignKey('product_collection_translation', 'product_collection_translation_id_product_collection_id');
        $this->dropForeignKey('product_collection_translation', 'product_collection_translation_id_product_collection_id_1');
        $this->dropForeignKey('product_product_collection', 'product_product_collection_collection_id_product_collection_id');
        $this->dropForeignKey('product_product_collection', 'product_product_collection_product_id_product_product_id');
        $this->removeIndex('product_collection_translation', 'product_collection_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('product_product_collection', 'product_product_collection_collection_id', array(
             'fields' => 
             array(
              0 => 'collection_id',
             ),
             ));
        $this->removeIndex('product_product_collection', 'product_product_collection_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}