<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('attachment_serwis1_attachment_translation');
        $this->dropTable('attachment_serwis5_attachment_translation');
        $this->dropTable('attachment_serwis6_attachment_translation');
        $this->dropTable('attachment_serwis7_attachment_translation');
        $this->createTable('attachment_serwis8_attachment', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'filename' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'extension' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('attachment_serwis8_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('attachment_serwis1_attachment', 'title', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis1_attachment', 'slug', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis1_attachment', 'description', 'clob', '', array(
             ));
        $this->addColumn('attachment_serwis5_attachment', 'title', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis5_attachment', 'slug', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis5_attachment', 'description', 'clob', '', array(
             ));
        $this->addColumn('attachment_serwis6_attachment', 'title', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis6_attachment', 'slug', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis6_attachment', 'description', 'clob', '', array(
             ));
        $this->addColumn('attachment_serwis7_attachment', 'title', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis7_attachment', 'slug', 'string', '255', array(
             ));
        $this->addColumn('attachment_serwis7_attachment', 'description', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->createTable('attachment_serwis1_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('attachment_serwis5_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('attachment_serwis6_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('attachment_serwis7_attachment_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('attachment_serwis8_attachment');
        $this->dropTable('attachment_serwis8_attachment_translation');
        $this->removeColumn('attachment_serwis1_attachment', 'title');
        $this->removeColumn('attachment_serwis1_attachment', 'slug');
        $this->removeColumn('attachment_serwis1_attachment', 'description');
        $this->removeColumn('attachment_serwis5_attachment', 'title');
        $this->removeColumn('attachment_serwis5_attachment', 'slug');
        $this->removeColumn('attachment_serwis5_attachment', 'description');
        $this->removeColumn('attachment_serwis6_attachment', 'title');
        $this->removeColumn('attachment_serwis6_attachment', 'slug');
        $this->removeColumn('attachment_serwis6_attachment', 'description');
        $this->removeColumn('attachment_serwis7_attachment', 'title');
        $this->removeColumn('attachment_serwis7_attachment', 'slug');
        $this->removeColumn('attachment_serwis7_attachment', 'description');
    }
}