<div class="row-fluid">
    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit layer') ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                     <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>
                        <?php echo $this->form->id ?>
                        <?php echo $this->form->text_html ?>
                        <?php echo $this->form->class ?>
                        <?php echo $this->form->animation ?>
                        <?php echo $this->form->easing ?>
                        <?php echo $this->form->speed ?>
                        <?php echo $this->form->start ?>
                        <?php echo $this->form->x_position ?>
                        <?php echo $this->form->y_position ?>
                        <?php echo $this->form->target_href ?>
                          <div class="tab-content">
                            <?php foreach($this->languages as $key => $language): ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">
                                <span class="section contentSection">
                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php echo $this->form->translations->getSubForm($language)->title ?>
                                <?php echo $this->form->translations->getSubForm($language)->content->setAttrib('class', 'tinymce') ?>
                            <?php endif; ?>
                                </span>
                                <span class="section metatagSection">
                                    <div class="title" style ="margin-top: 30px;">

                                        <h4>
                                            <span class="icon16 icomoon-icon-pencil"></span>
                                            <span><?php echo $this->translate('Metatags') ?></span>
                                        </h4>

                                    </div>
                                    <div class="content clearfix">
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_title; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_description; ?>
                                        <?php echo $this->form->metatags->translations->getSubForm($language)->meta_keywords; ?>
                                    </div>
                                </span>
                            </div>
                            <?php endforeach; ?>
                        </div>
                         
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('edit-slide', 'slider', array('slider' => $this->slide->getSliderId(), 'id' => $this->slide->getId())) ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                    </form>
            </div>
            
        </div>
        
</div>