<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#layer_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-layer-data', 'slider') ?>/id/<?php echo $this->slide->getId(); ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            { "bSortable": false, sWidth: '300px' },
            { "bSortable": false, sWidth: '150px' },
            { "bSortable": false, sWidth: '150px' },
            { "bSortable": false, sWidth: '150px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#layer_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    $("#layer_table").delegate(".remove2", "click", function(e) {
            e.preventDefault();
            var link = $(this).attr("href");
            if(confirm("Czy na pewno chcesz usunąć?")) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: link,
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            //$("#main_photo_con").html(resp.body);
                            $("#layer_table").trigger('update');
                        }
                    }
                });
            }
     }); 
    
    $("#layer_table").delegate("td .move", "click", function(e) {
        e.preventDefault();
        $.ajax({
            url: $(this).attr("href"),
            type: "post",
            dataType: "json",
            data: {format: "json"},
            success: function (resp) {
                $("#layer_table").trigger("update");
            }
        });
    });
    
    $('.target').hide();
    var selected_input = $('#target_type-element input:checked');
    $('#'+selected_input.val()).show();
      $('#target_type-element input').click(function(){
        $('.target').hide();
        $('#'+$(this).val()).show();
    });
    
});
</script>
<style>
    #target_type-label{
        display:inline-block;
        width:300px;
    }
    #target_type-element{
        display:inline-block;
    }
    #target_type-element label{
        display:inline-block;
        width:200px;
    }
    #target_type-element br{
        display:none;
    }
</style>
<div class="row-fluid">
    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit slide') ?></span>
                </h4>
                
            </div>
            
            <div class="content clearfix">
                
                    <div class="banner">
                         <a id="main_photo" href="/media/photos/<?php echo $this->slide->get('PhotoRoot')->getOffset() ?>/<?php echo $this->slide->get('PhotoRoot')->getFilename() ?>" rel="prettyPhoto" title="<?php echo $this->slide->get('PhotoRoot')->getTitle() ?>">
                            <img src="/media/photos/<?php echo $this->slide->get('PhotoRoot')->getOffset() ?>/126x126/<?php echo $this->slide->get('PhotoRoot')->getFilename() ?>" data-original="/media/photos/<?php echo $this->slide->get('PhotoRoot')->getOffset() ?>/<?php echo $this->slide->get('PhotoRoot')->getFilename() ?>" alt="<?php echo $this->slide->get('PhotoRoot')->getTitle() ?>">
                        </a>
                    </div>
                
                     <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">

                        <?php
                        foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        }
                        ?>
                        <?php echo $this->form->id ?>
                        <?php //echo $this->form->transition ?>
                        <?php //echo $this->form->slot_amount ?>
                        <?php //echo $this->form->rotation ?>
                        <?php //echo $this->form->transition_duration ?>
                        <?php //echo $this->form->delay ?>
                        <?php //echo $this->form->enable_link ?>
                         <br /><br />
                        <?php echo $this->form->target_type ?>
                         
                         <span class="target" id="custom_target">
                                <?php echo $this->form->target_href ?>
                         </span>
                         <span class="target" id="news_target">
                                <?php echo $this->form->news_id ?>
                         </span>
                         <span class="target" id="stream_target">
                                <?php echo $this->form->stream_id ?>
                         </span>
                            <?php $language = "pl"; ?>
                            <div class="tab-pane<?php if($language == $this->adminLanguage->getId()): ?> in active<?php endif; ?>" id="dropdown<?php echo $key + 1 ?>">
                                <span class="section contentSection">
                            <?php if($this->form->translations->getSubForm($language)): ?>
                                <?php //echo $this->form->translations->getSubForm($language)->title->setLabel('Naglówek') ?>
                                <?php echo $this->form->translations->getSubForm($language)->content->setAttrib('class', 'tinymce')->setLabel('Tytuł') ?>
                            <?php endif; ?>
                                </span>
                               
                            </div>
                         
                         <br /><br />
                        
                         <div class="clearfix"></div>

                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('list-slide', 'slider') ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>
                    </form>
            </div>
            
        </div>
        
</div>