<script type="text/javascript">
$(document).ready(function() {
    $("#add_slide").click(function(e) {
        e.preventDefault();
        $("#explorer-content").show();
        var elf = $('#elfinder').elfinder({
            url : '/admin/media/elfinder',  // connector URL (REQUIRED)
            getFileCallback : function(href) {
                var data = { hrefs: href, slider: "main" };
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "<?php echo $this->adminUrl('add-slide-photo', 'slider') ?>",
                    data: data,
                    success: function(resp) {
                        if(resp.status == "success") {
                            $("#slide_container").html(resp.body);
                            $("#itemContainer").trigger("update");
                        }
                    }
                });

                $('#explorer').dialog('close');
            },
            commandsOptions : {
                // configure value for "getFileCallback" used for editor integration
                getfile : {
                    // allow to return folders info
                    onlyURL  : true,

                    // allow to return multiple files info
                    multiple : true,

                    // allow to return folders info
                    folders  : false,

                    // action after callback (close/destroy)
                    oncomplete : ''
                },
            }
        }).elfinder('instance');	
        
        $('#explorer').dialog('open');
    });
    
    
    
    
    $("#itemContainer").delegate(".move", "click", function(e) {
        e.preventDefault();
        var link = $(this);
        $.ajax({
            type: "post",
            dataType: "json",
            url: $(link).attr("href"),
            success: function(resp) {
                if(resp.status == "success") {
                    $("#slide_container").html(resp.body);
                    $("#itemContainer").trigger("update");
                }
            }
        });
    });
    
    $("#itemContainer").delegate(".delete", "click", function(e) {
        e.preventDefault();
        var link = $(this);
        $.ajax({
            type: "post",
            dataType: "json",
            url: $(link).attr("href"),
            success: function(resp) {
                if(resp.status == "success") {
                    $("#slide_container").html(resp.body);
                    $("#itemContainer").trigger("update");
                }
            }
        });
    });
    
    $('#explorer').dialog({
		autoOpen: false,
		modal: true,
		dialogClass: 'dialog',
	});
});
</script>

<div class="row-fluid">

    <div class="span6">

        <?php if(count($this->sliderConfig)): ?>
        <div class="centerContent">
            <ul class="bigBtnIcon choose-buttons">
                <?php foreach($this->sliderConfig as $id => $name): ?>
                <li>
                    <a href="<?php echo $this->adminUrl('list-slide', 'slider', array('slider' => $id)) ?>" title="<?php echo $this->translate('Edit') ?>" class="tipB <?php if($id == $this->slider->getId()): ?>active<?php endif; ?>">
                        <span class="icon entypo-icon-images"></span>
                        <span class="txt"><?php echo $this->translate($name) ?></span>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div><!-- End .span6 -->  
        <?php endif; ?>

    </div><!-- End .span6 -->  
    
</div>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil-2"></span>
                    <span><?php echo $this->translate('Slides') ?> wymiary <?php echo $this->photoDimension; ?></span>
                    <div class="box-form right">
                        <a href="#" id="add_slide" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">

                <div id="itemContainer">
                    <ul id="slide_container" class="galleryView center">
                        <?php if($this->slides): ?>
                        <?php echo $this->partial('admin/slider-slide-photos.phtml', 'slider', array('slides' => $this->slides, 'slider' => $this->slider)) ?>
                        <?php else: ?>
                        <li class="pull-left">
                            <a href="/images/gallery/1.jpg" rel="prettyPhoto" title="<?php echo $this->translate('No photo') ?>">
                                <img src="/images/gallery/preload.png" data-original="/images/gallery/thumbnails/1.jpg" alt="<?php echo $this->translate('No photo') ?>">
                            </a>
                            <div class="actionBtn">
                                <a href="#" class="add"><span class="icon16 iconic-icon-cursor white"></span></a>
                            </div>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
                
            </div>

        </div><!-- End .box -->

    </div>

</div>

<div id="explorer" class="dialog"><div id="elfinder"></div></div>
    