<?php

/**
 * Slider_Model_Doctrine_SlideTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Slider_Model_Doctrine_SlideTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Slider_Model_Doctrine_SlideTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slider_Model_Doctrine_SlideTranslation');
    }
}