<?php

/**
 * Slider_Model_Doctrine_SlideTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Slider
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Slider_Model_Doctrine_SlideTranslation extends Slider_Model_Doctrine_BaseSlideTranslation
{

}