<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('slider_slide');
        $this->dropTable('slider_slider');
        $this->createTable('slider_slide_serwis5', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'slider_id' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'title_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_bg_width' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_height' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'animation' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'target_href' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slide_serwis6', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'slider_id' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'title_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_bg_width' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_height' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'animation' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'target_href' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slide_serwis7', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'slider_id' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'title_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_bg_width' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_height' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'animation' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'target_href' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slide_serwis8', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'slider_id' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'title_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_bg_width' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_height' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'animation' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'target_href' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slider_serwis5', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '128',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slide_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slider_serwis6', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '128',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slide_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slider_serwis7', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '128',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slide_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slider_serwis8', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '128',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slide_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->createTable('slider_slide', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'slider_id' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'title_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'title_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description_pos_x' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_pos_y' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_size' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_color' => 
             array(
              'type' => 'string',
              'length' => '12',
             ),
             'description_bg_width' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'description_bg_height' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'animation' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'photo_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'target_href' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'root_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'lft' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'rgt' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('slider_slider', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'string',
              'length' => '128',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'slide_root_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'type' => 'MyISAM',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('slider_slide_serwis5');
        $this->dropTable('slider_slide_serwis6');
        $this->dropTable('slider_slide_serwis7');
        $this->dropTable('slider_slide_serwis8');
        $this->dropTable('slider_slider_serwis5');
        $this->dropTable('slider_slider_serwis6');
        $this->dropTable('slider_slider_serwis7');
        $this->dropTable('slider_slider_serwis8');
    }
}