<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('slider_slide', 'title_pos_x', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'title_pos_y', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'title_color', 'string', '12', array(
             ));
        $this->addColumn('slider_slide', 'title_size', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'description', 'string', '255', array(
             ));
        $this->addColumn('slider_slide', 'description_pos_x', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'description_pos_y', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'description_color', 'string', '12', array(
             ));
        $this->addColumn('slider_slide', 'description_size', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'description_bg_color', 'string', '12', array(
             ));
        $this->addColumn('slider_slide', 'description_bg_width', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'description_bg_height', 'integer', '4', array(
             ));
        $this->addColumn('slider_slide', 'animation', 'string', '255', array(
             ));
        $this->changeColumn('slider_slide', 'target_href', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('slider_slide', 'title_pos_x');
        $this->removeColumn('slider_slide', 'title_pos_y');
        $this->removeColumn('slider_slide', 'title_color');
        $this->removeColumn('slider_slide', 'title_size');
        $this->removeColumn('slider_slide', 'description');
        $this->removeColumn('slider_slide', 'description_pos_x');
        $this->removeColumn('slider_slide', 'description_pos_y');
        $this->removeColumn('slider_slide', 'description_color');
        $this->removeColumn('slider_slide', 'description_size');
        $this->removeColumn('slider_slide', 'description_bg_color');
        $this->removeColumn('slider_slide', 'description_bg_width');
        $this->removeColumn('slider_slide', 'description_bg_height');
        $this->removeColumn('slider_slide', 'animation');
    }
}